/** Chinese (Simplified) translations of Bible section headings */
const HEADINGS_ZH: Record<string, string> = {
  "The Creation of the World": "创造世界",
  "The Fourth Day: Sun, Moon, and Stars": "第四日：日、月、星辰",
  "The Sixth Day: Land Animals and Humans": "第六日：陆地动物与人类",
  "The Seventh Day: God Rests": "第七日：神安息",
  "The Garden of Eden": "伊甸园",
  "The Creation of Woman": "造女人",
  "The Fall of Man": "人的堕落",
  "God's Judgment": "神的审判",
  "Banished from the Garden": "被逐出伊甸园",
  "Cain and Abel": "该隐和亚伯",
  "The Line of Cain": "该隐的后代",
  "Seth and Enosh": "塞特和以挪士",
  "From Adam to Noah": "从亚当到挪亚",
  "Wickedness in the World": "世上的罪恶",
  "Noah and the Ark": "挪亚和方舟",
  "The Great Flood": "大洪水",
  "The Flood Recedes": "洪水消退",
  "God's Promise to Noah": "神对挪亚的应许",
  "God's Covenant with Noah": "神与挪亚立约",
  "Noah's Sons": "挪亚的儿子们",
  "The Table of Nations": "万国谱系",
  "The Tower of Babel": "巴别塔",
  "From Shem to Abram": "从闪到亚伯兰",
  "The Call of Abram": "亚伯兰蒙召",
  "Abram in Egypt": "亚伯兰在埃及",
  "God's Covenant with Abram": "神与亚伯兰立约",
  "The Covenant of Circumcision": "割礼之约",
  "The Promise of Isaac": "以撒的应许",
  "Three Visitors": "三位来客",
  "Abraham Pleads for Sodom": "亚伯拉罕为所多玛代求",
  "The Destruction of Sodom and Gomorrah": "所多玛和蛾摩拉的毁灭",
  "Lot's Daughters": "罗得的女儿们",
  "The Birth of Isaac": "以撒的出生",
  "Hagar and Ishmael Sent Away": "夏甲和以实玛利被遣走",
  "The Sacrifice of Isaac": "亚伯拉罕献以撒",
  "Isaac and Rebekah": "以撒和利百加",
  "Jacob and Esau": "雅各和以扫",
  "Esau Sells His Birthright": "以扫出卖长子名分",
  "Jacob Steals Esau's Blessing": "雅各骗取以扫的祝福",
  "Jacob's Dream at Bethel": "雅各在伯特利的梦",
  "Jacob Wrestles with God": "雅各与神摔跤",
  "Joseph's Dreams": "约瑟的梦",
  "Joseph Sold by His Brothers": "约瑟被兄弟们出卖",
  "Joseph in Potiphar's House": "约瑟在波提乏家",
  "Joseph Interprets Dreams in Prison": "约瑟在狱中解梦",
  "Pharaoh's Dreams": "法老的梦",
  "Joseph Made Ruler of Egypt": "约瑟被立为埃及的宰相",
  "Joseph Reveals Himself to His Brothers": "约瑟向兄弟们表明身份",
  "The Death of Jacob": "雅各之死",
  "Joseph Reassures His Brothers": "约瑟安慰他的兄弟们",
  "Israel Oppressed in Egypt": "以色列人在埃及受压迫",
  "The Hebrew Midwives": "希伯来的收生婆",
  "The Birth of Moses": "摩西的出生",
  "Moses Flees to Midian": "摩西逃往米甸",
  "The Burning Bush": "燃烧的荆棘",
  "The First Plague: Water to Blood": "第一灾：水变血",
  "The Passover": "逾越节",
  "The Tenth Plague: Death of the Firstborn": "第十灾：击杀长子",
  "Crossing the Red Sea": "过红海",
  "The Ten Commandments": "十诫",
  "The Way of the Righteous and the Wicked": "义人与恶人的道路",
  "The Lord Is My Shepherd": "耶和华是我的牧者",
  "A Prayer of Repentance": "悔罪之祷",
  "Abiding in the Shadow of the Almighty": "住在至高者的隐密处",
  "A Psalm of Thanksgiving": "感恩之诗",
  "The Glories of God's Word": "神话语的荣美",
  "Beth": "Beth",
  "Gimel": "Gimel",
  "Daleth": "Daleth",
  "He": "He",
  "Waw": "Waw",
  "Zayin": "Zayin",
  "Heth": "Heth",
  "Teth": "Teth",
  "Yodh": "Yodh",
  "Kaph": "Kaph",
  "Lamedh": "Lamedh",
  "Mem": "Mem",
  "Nun": "Nun",
  "Samekh": "Samekh",
  "Ayin": "Ayin",
  "Pe": "Pe",
  "Tsadhe": "Tsadhe",
  "Qoph": "Qoph",
  "Resh": "Resh",
  "Sin and Shin": "Sin and Shin",
  "Taw": "Taw",
  "God's Perfect Knowledge": "神完全的知识",
  "Praise the Lord!": "赞美耶和华！",
  "The Purpose of Proverbs": "箴言的宗旨",
  "A Father's Instruction": "父亲的教训",
  "Wisdom Calls Out": "智慧的呼唤",
  "Trust in the Lord": "信靠耶和华",
  "The Value of Wisdom": "智慧的价值",
  "The Words of King Lemuel": "利慕伊勒王的言语",
  "The Virtuous Woman": "才德的妇人",
  "Isaiah's Vision of the Lord": "以赛亚看见主的异象",
  "The Sign of Immanuel": "以马内利的兆头",
  "A Child Is Born": "有一婴孩为我们而生",
  "Comfort for God's People": "安慰神的百姓",
  "The Everlasting God": "永在的神",
  "The Suffering Servant": "受苦的仆人",
  "An Invitation to the Thirsty": "邀请干渴的人",
  "The Genealogy of Jesus": "耶稣的家谱",
  "The Birth of Jesus Christ": "耶稣基督的降生",
  "The Visit of the Wise Men": "博士来访",
  "The Flight to Egypt": "逃往埃及",
  "Herod Kills the Children": "希律屠杀婴孩",
  "John the Baptist Prepares the Way": "施洗约翰预备道路",
  "The Baptism of Jesus": "耶稣受洗",
  "The Temptation of Jesus": "耶稣受试探",
  "Jesus Begins His Ministry": "耶稣开始传道",
  "Jesus Calls His First Disciples": "耶稣呼召首批门徒",
  "The Sermon on the Mount": "登山宝训",
  "The Beatitudes": "八福",
  "Salt and Light": "盐和光",
  "Christ Fulfills the Law": "基督成全律法",
  "Teaching About Anger": "论怒气",
  "Teaching About Lust": "论情欲",
  "Teaching About Oaths": "论起誓",
  "Teaching About Retaliation": "论报复",
  "Love Your Enemies": "爱仇敌",
  "Teaching About Giving": "论施舍",
  "Teaching About Prayer": "论祷告",
  "The Lord's Prayer": "主祷文",
  "Teaching About Fasting": "论禁食",
  "Treasures in Heaven": "积财宝在天上",
  "Do Not Worry": "不要忧虑",
  "Do Not Judge": "不要论断人",
  "Ask, Seek, Knock": "祈求、寻找、叩门",
  "The Narrow Gate": "窄门",
  "A Tree and Its Fruit": "树和果子",
  "Build Your House on the Rock": "把房子建在磐石上",
  "Jesus Heals a Leper": "耶稣洁净麻风病人",
  "The Centurion's Faith": "百夫长的信心",
  "Jesus Heals Many": "耶稣医治许多人",
  "Jesus Calms the Storm": "耶稣平静风浪",
  "Jesus Heals Two Demon-Possessed Men": "耶稣医治两个被鬼附的人",
  "The Parable of the Sower": "撒种的比喻",
  "The Parable of the Weeds": "稗子的比喻",
  "The Parables of the Mustard Seed and Leaven": "芥菜种和面酵的比喻",
  "The Parables of Hidden Treasure and the Pearl": "藏宝和寻珠的比喻",
  "The Death of John the Baptist": "施洗约翰之死",
  "Jesus Feeds Five Thousand": "耶稣喂饱五千人",
  "Jesus Walks on Water": "耶稣在水面上行走",
  "Peter's Confession of Christ": "彼得认信基督",
  "Jesus Predicts His Death": "耶稣预言自己的死",
  "Take Up Your Cross": "背起你的十字架",
  "The Transfiguration": "登山变像",
  "Who Is the Greatest?": "谁是最大的？",
  "The Parable of the Lost Sheep": "迷羊的比喻",
  "The Parable of the Unforgiving Servant": "不饶恕人的仆人的比喻",
  "Teaching About Divorce": "论休妻",
  "Jesus Blesses the Children": "耶稣为小孩子祝福",
  "The Rich Young Man": "富有的少年人",
  "The Parable of the Workers in the Vineyard": "葡萄园工人的比喻",
  "Jesus Heals Two Blind Men": "耶稣医治两个瞎子",
  "The Triumphal Entry": "荣入圣城",
  "Jesus Cleanses the Temple": "耶稣洁净圣殿",
  "The Parable of the Wedding Feast": "婚宴的比喻",
  "Paying Taxes to Caesar": "纳税给凯撒",
  "The Greatest Commandment": "最大的诫命",
  "Jesus Foretells the Future": "耶稣预言未来",
  "No One Knows the Day or Hour": "无人知道那日子和时辰",
  "The Parable of the Ten Virgins": "十个童女的比喻",
  "The Parable of the Talents": "按才受托的比喻",
  "The Final Judgment": "最后的审判",
  "The Plot to Kill Jesus": "谋害耶稣的阴谋",
  "The Last Supper": "最后的晚餐",
  "Jesus Prays in Gethsemane": "耶稣在客西马尼园祷告",
  "The Betrayal and Arrest of Jesus": "耶稣被出卖和被捕",
  "Jesus Before the Council": "耶稣在公会前受审",
  "Peter Denies Jesus": "彼得否认耶稣",
  "Jesus Before Pilate": "耶稣在彼拉多面前",
  "Jesus Is Mocked": "耶稣被戏弄",
  "The Crucifixion": "钉十字架",
  "The Burial of Jesus": "耶稣的安葬",
  "The Resurrection": "复活",
  "The Great Commission": "大使命",
  "Jesus Drives Out an Unclean Spirit": "耶稣赶出污鬼",
  "Jesus Heals a Demon-Possessed Man": "耶稣医治被鬼附的人",
  "Jesus Heals a Woman and Raises a Girl": "耶稣医治患病的女人并使女孩复活",
  "Jesus Rejected at Nazareth": "耶稣在拿撒勒被厌弃",
  "Blind Bartimaeus": "瞎子巴底买",
  "Introduction": "引言",
  "The Birth of John the Baptist Foretold": "预言施洗约翰的出生",
  "The Birth of Jesus Foretold": "预言耶稣的降生",
  "Mary Visits Elizabeth": "马利亚探访以利沙伯",
  "Mary's Song of Praise": "马利亚的颂歌",
  "The Birth of John the Baptist": "施洗约翰的出生",
  "Zechariah's Prophecy": "撒迦利亚的预言",
  "The Birth of Jesus": "耶稣的降生",
  "The Shepherds and the Angels": "牧羊人和天使",
  "Jesus Presented at the Temple": "耶稣被献于圣殿",
  "The Boy Jesus at the Temple": "少年耶稣在圣殿",
  "Jesus Sends Out the Seventy-Two": "耶稣差遣七十二人",
  "The Parable of the Good Samaritan": "好撒玛利亚人的比喻",
  "Jesus Visits Martha and Mary": "耶稣探访马大和马利亚",
  "The Parable of the Lost Coin": "失钱的比喻",
  "The Parable of the Prodigal Son": "浪子的比喻",
  "Jesus Prays on the Mount of Olives": "耶稣在橄榄山上祷告",
  "Jesus Before Pilate and Herod": "耶稣在彼拉多和希律面前",
  "The Death of Jesus": "耶稣之死",
  "On the Road to Emmaus": "以马忤斯的路上",
  "Jesus Appears to His Disciples": "耶稣向门徒显现",
  "The Ascension": "耶稣升天",
  "The Word Became Flesh": "道成肉身",
  "The Testimony of John the Baptist": "施洗约翰的见证",
  "Jesus Calls Philip and Nathanael": "耶稣呼召腓力和拿但业",
  "The Wedding at Cana": "迦拿的婚宴",
  "Jesus and Nicodemus": "耶稣和尼哥底母",
  "For God So Loved the World": "神爱世人",
  "John the Baptist Exalts Christ": "施洗约翰尊崇基督",
  "Jesus and the Woman at the Well": "耶稣与井旁的妇人",
  "Jesus Heals an Official's Son": "耶稣医治大臣的儿子",
  "Jesus Heals at the Pool of Bethesda": "耶稣在毕士大池旁医治病人",
  "The Authority of the Son": "子的权柄",
  "Jesus the Bread of Life": "耶稣是生命的粮",
  "Many Disciples Turn Away": "许多门徒退去",
  "Jesus at the Feast of Tabernacles": "耶稣在住棚节",
  "Rivers of Living Water": "活水的江河",
  "The Woman Caught in Adultery": "行淫时被捉的妇人",
  "Jesus the Light of the World": "耶稣是世界的光",
  "The Truth Will Set You Free": "真理必叫你们得自由",
  "Jesus Heals a Man Born Blind": "耶稣医治生来瞎眼的人",
  "Jesus the Good Shepherd": "耶稣是好牧人",
  "Jesus at the Feast of Dedication": "耶稣在修殿节",
  "The Death of Lazarus": "拉撒路之死",
  "Jesus Comforts Martha and Mary": "耶稣安慰马大和马利亚",
  "Jesus Raises Lazarus": "耶稣使拉撒路复活",
  "Mary Anoints Jesus": "马利亚膏耶稣",
  "Jesus Washes the Disciples' Feet": "耶稣为门徒洗脚",
  "Jesus Predicts His Betrayal": "耶稣预言自己被卖",
  "A New Commandment": "新命令",
  "Jesus Predicts Peter's Denial": "耶稣预言彼得否认他",
  "Jesus Comforts His Disciples": "耶稣安慰门徒",
  "I Am the Way, the Truth, and the Life": "我就是道路、真理、生命",
  "The Promise of the Holy Spirit": "应许赐圣灵",
  "I Am the True Vine": "我是真葡萄树",
  "The Greatest Love": "最大的爱",
  "The World's Hatred": "世人的恨",
  "The Work of the Holy Spirit": "圣灵的工作",
  "Sorrow Will Turn to Joy": "忧愁变为喜乐",
  "Jesus Has Overcome the World": "耶稣已经胜了世界",
  "Jesus Prays for Himself": "耶稣为自己祷告",
  "Jesus Prays for His Disciples": "耶稣为门徒祷告",
  "Jesus Prays for All Believers": "耶稣为所有信徒祷告",
  "Jesus Before the High Priest": "耶稣在大祭司面前",
  "Jesus Sentenced to Be Crucified": "耶稣被判钉十字架",
  "The Empty Tomb": "空坟墓",
  "Jesus Appears to Mary Magdalene": "耶稣向抹大拉的马利亚显现",
  "Jesus and Thomas": "耶稣和多马",
  "Jesus Appears at the Sea of Galilee": "耶稣在加利利海边显现",
  "Jesus Restores Peter": "耶稣恢复彼得",
  "Matthias Chosen to Replace Judas": "拣选马提亚代替犹大",
  "The Day of Pentecost": "五旬节",
  "Peter's Sermon": "彼得的讲道",
  "The First Believers": "最初的信徒",
  "The Fellowship of Believers": "信徒的团契",
  "Peter Heals a Lame Man": "彼得医治瘸腿的人",
  "Peter Speaks in Solomon's Portico": "彼得在所罗门廊下讲道",
  "The Conversion of Saul": "扫罗的归信",
  "Saul Begins to Preach": "扫罗开始传道",
  "Peter and Cornelius": "彼得和哥尼流",
  "Paul in Thessalonica and Berea": "保罗在帖撒罗尼迦和庇哩亚",
  "Paul in Athens": "保罗在雅典",
  "Greetings from Paul": "保罗的问候",
  "The Righteous Shall Live by Faith": "义人必因信得生",
  "God's Wrath Against Sin": "神向罪发怒",
  "God's Faithfulness": "神的信实",
  "Righteousness Through Faith": "因信称义",
  "Peace with God Through Faith": "因信与神和好",
  "Death Through Adam, Life Through Christ": "因亚当而死，因基督而生",
  "Dead to Sin, Alive in Christ": "向罪死，在基督里活",
  "Slaves to Righteousness": "作义的奴仆",
  "The Struggle with Sin": "与罪的挣扎",
  "Life in the Spirit": "在圣灵里的生活",
  "Future Glory": "将来的荣耀",
  "More Than Conquerors": "得胜有余",
  "Salvation for All Who Believe": "凡信的人都得救",
  "How Beautiful Are the Feet": "报福音的人，他们的脚踪何等佳美",
  "A Living Sacrifice": "活祭",
  "Marks of a True Christian": "真基督徒的标志",
  "Submission to Authorities": "顺服掌权者",
  "Love Fulfills the Law": "爱成全律法",
  "The Way of Love": "爱的真谛",
  "The Resurrection of Christ": "基督的复活",
  "The Resurrection Body": "复活的身体",
  "The Mystery of the Last Trumpet": "末次号筒的奥秘",
  "Freedom in Christ": "基督里的自由",
  "Walking by the Spirit": "靠圣灵行事",
  "The Fruit of the Spirit": "圣灵的果子",
  "Made Alive in Christ": "在基督里活过来",
  "Unity in Christ": "在基督里合一",
  "Unity in the Body of Christ": "在基督的身体里合一",
  "The New Life": "新生活",
  "Children and Parents": "儿女与父母",
  "The Armor of God": "神的全副军装",
  "Christ's Example of Humility": "基督谦卑的榜样",
  "Shining as Lights in the World": "在世上作光明的子女",
  "Rejoice in the Lord Always": "常常在主里喜乐",
  "Do Not Be Anxious": "应当一无挂虑",
  "God's Provision": "神的供应",
  "By Faith": "因着信",
  "The Race of Faith": "信心的赛程",
  "God's Discipline": "神的管教",
  "Greeting": "问安",
  "Testing of Your Faith": "信心的试炼",
  "Hearing and Doing the Word": "听道与行道",
  "Do Not Show Favoritism": "不可偏心待人",
  "Faith and Works": "信心与行为",
  "Taming the Tongue": "勒住舌头",
  "Walking in the Light": "行在光明中",
  "Children of God": "神的儿女",
  "Test the Spirits": "试验诸灵",
  "God Is Love": "神就是爱",
  "Prologue": "序言",
  "Vision of the Son of Man": "人子的异象",
  "The Throne in Heaven": "天上的宝座",
  "The Scroll and the Lamb": "书卷和羔羊",
  "A Great Multitude from Every Nation": "各国各族的大群众",
  "The Marriage Supper of the Lamb": "羔羊的婚宴",
  "The Rider on the White Horse": "骑白马的",
  "The Thousand Years": "千禧年",
  "The Great White Throne Judgment": "白色大宝座的审判",
  "A New Heaven and a New Earth": "新天新地",
  "The New Jerusalem": "新耶路撒冷",
  "The River of Life": "生命河",
  "Jesus Is Coming Soon": "耶稣快来了",
};
export default HEADINGS_ZH;
