/** Arabic translations of Bible section headings */
const HEADINGS_AR: Record<string, string> = {
  // ============ GENESIS ============
  "The Creation of the World": "خلق العالم",
  "The Fourth Day: Sun, Moon, and Stars": "اليوم الرابع: الشمس والقمر والنجوم",
  "The Sixth Day: Land Animals and Humans": "اليوم السادس: حيوانات البر والإنسان",
  "The Seventh Day: God Rests": "اليوم السابع: الله يستريح",
  "The Garden of Eden": "جنة عدن",
  "The Creation of Woman": "خلق المرأة",
  "The Fall of Man": "سقوط الإنسان",
  "God's Judgment": "دينونة الله",
  "Banished from the Garden": "الطرد من الجنة",
  "Cain and Abel": "قايين وهابيل",
  "The Line of Cain": "نسل قايين",
  "Seth and Enosh": "شيث وأنوش",
  "From Adam to Noah": "من آدم إلى نوح",
  "Wickedness in the World": "الشر في العالم",
  "Noah and the Ark": "نوح والفلك",
  "The Great Flood": "الطوفان العظيم",
  "The Flood Recedes": "انحسار مياه الطوفان",
  "God's Promise to Noah": "وعد الله لنوح",
  "God's Covenant with Noah": "عهد الله مع نوح",
  "Noah's Sons": "أبناء نوح",
  "The Table of Nations": "جدول الأمم",
  "The Tower of Babel": "برج بابل",
  "From Shem to Abram": "من سام إلى أبرام",
  "The Call of Abram": "دعوة أبرام",
  "Abram in Egypt": "أبرام في مصر",
  "God's Covenant with Abram": "عهد الله مع أبرام",
  "The Covenant of Circumcision": "عهد الختان",
  "The Promise of Isaac": "الوعد بإسحاق",
  "Three Visitors": "الزوار الثلاثة",
  "Abraham Pleads for Sodom": "إبراهيم يتشفع لسدوم",
  "The Destruction of Sodom and Gomorrah": "دمار سدوم وعمورة",
  "Lot's Daughters": "بنتا لوط",
  "The Birth of Isaac": "ولادة إسحاق",
  "Hagar and Ishmael Sent Away": "طرد هاجر وإسماعيل",
  "The Sacrifice of Isaac": "ذبيحة إسحاق",
  "Isaac and Rebekah": "إسحاق ورفقة",
  "Jacob and Esau": "يعقوب وعيسو",
  "Esau Sells His Birthright": "عيسو يبيع بكوريته",
  "Jacob Steals Esau's Blessing": "يعقوب يسرق بركة عيسو",
  "Jacob's Dream at Bethel": "حلم يعقوب في بيت إيل",
  "Jacob Wrestles with God": "يعقوب يصارع الله",
  "Joseph's Dreams": "أحلام يوسف",
  "Joseph Sold by His Brothers": "إخوة يوسف يبيعونه",
  "Joseph in Potiphar's House": "يوسف في بيت فوطيفار",
  "Joseph Interprets Dreams in Prison": "يوسف يفسر الأحلام في السجن",
  "Pharaoh's Dreams": "أحلام فرعون",
  "Joseph Made Ruler of Egypt": "يوسف يصبح حاكمًا على مصر",
  "Joseph Reveals Himself to His Brothers": "يوسف يكشف عن نفسه لإخوته",
  "The Death of Jacob": "موت يعقوب",
  "Joseph Reassures His Brothers": "يوسف يطمئن إخوته",

  // ============ EXODUS ============
  "Israel Oppressed in Egypt": "اضطهاد إسرائيل في مصر",
  "The Hebrew Midwives": "القابلتان العبرانيتان",
  "The Birth of Moses": "ولادة موسى",
  "Moses Flees to Midian": "هروب موسى إلى مديان",
  "The Burning Bush": "العليقة المشتعلة",
  "The First Plague: Water to Blood": "الضربة الأولى: تحويل الماء إلى دم",
  "The Passover": "الفصح",
  "The Tenth Plague: Death of the Firstborn": "الضربة العاشرة: موت الأبكار",
  "Crossing the Red Sea": "عبور البحر الأحمر",
  "The Ten Commandments": "الوصايا العشر",

  // ============ PSALMS ============
  "The Way of the Righteous and the Wicked": "طريق الأبرار والأشرار",
  "The Lord Is My Shepherd": "الرب راعيّ",
  "A Prayer of Repentance": "صلاة توبة",
  "Abiding in the Shadow of the Almighty": "الاحتماء بظل القدير",
  "A Psalm of Thanksgiving": "مزمور شكر",
  "The Glories of God's Word": "أمجاد كلمة الله",
  "Beth": "Beth",
  "Gimel": "Gimel",
  "Daleth": "Daleth",
  "He": "He",
  "Waw": "Waw",
  "Zayin": "Zayin",
  "Heth": "Heth",
  "Teth": "Teth",
  "Yodh": "Yodh",
  "Kaph": "Kaph",
  "Lamedh": "Lamedh",
  "Mem": "Mem",
  "Nun": "Nun",
  "Samekh": "Samekh",
  "Ayin": "Ayin",
  "Pe": "Pe",
  "Tsadhe": "Tsadhe",
  "Qoph": "Qoph",
  "Resh": "Resh",
  "Sin and Shin": "Sin and Shin",
  "Taw": "Taw",
  "God's Perfect Knowledge": "علم الله الكامل",
  "Praise the Lord!": "سبحوا الرب!",

  // ============ PROVERBS ============
  "The Purpose of Proverbs": "الغرض من الأمثال",
  "A Father's Instruction": "تعليم الأب",
  "Wisdom Calls Out": "الحكمة تنادي",
  "Trust in the Lord": "توكل على الرب",
  "The Value of Wisdom": "قيمة الحكمة",
  "The Words of King Lemuel": "كلمات الملك لموئيل",
  "The Virtuous Woman": "المرأة الفاضلة",

  // ============ ISAIAH ============
  "Isaiah's Vision of the Lord": "رؤيا إشعياء للرب",
  "The Sign of Immanuel": "آية عمانوئيل",
  "A Child Is Born": "يولد لنا ولد",
  "Comfort for God's People": "تعزية لشعب الله",
  "The Everlasting God": "الإله الأزلي",
  "The Suffering Servant": "العبد المتألم",
  "An Invitation to the Thirsty": "دعوة للعطاش",

  // ============ MATTHEW ============
  "The Genealogy of Jesus": "نسب يسوع المسيح",
  "The Birth of Jesus Christ": "ولادة يسوع المسيح",
  "The Visit of the Wise Men": "زيارة المجوس",
  "The Flight to Egypt": "الهروب إلى مصر",
  "Herod Kills the Children": "هيرودس يقتل الأطفال",
  "John the Baptist Prepares the Way": "يوحنا المعمدان يعد الطريق",
  "The Baptism of Jesus": "معمودية يسوع",
  "The Temptation of Jesus": "تجربة يسوع",
  "Jesus Begins His Ministry": "يسوع يبدأ خدمته",
  "Jesus Calls His First Disciples": "يسوع يدعو تلاميذه الأولين",
  "The Sermon on the Mount": "الموعظة على الجبل",
  "The Beatitudes": "التطويبات",
  "Salt and Light": "الملح والنور",
  "Christ Fulfills the Law": "المسيح يكمل الناموس",
  "Teaching About Anger": "تعليم عن الغضب",
  "Teaching About Lust": "تعليم عن الشهوة",
  "Teaching About Oaths": "تعليم عن الأقسام",
  "Teaching About Retaliation": "تعليم عن الانتقام",
  "Love Your Enemies": "أحبوا أعداءكم",
  "Teaching About Giving": "تعليم عن العطاء",
  "Teaching About Prayer": "تعليم عن الصلاة",
  "The Lord's Prayer": "الصلاة الربانية",
  "Teaching About Fasting": "تعليم عن الصوم",
  "Treasures in Heaven": "كنوز في السماء",
  "Do Not Worry": "لا تقلقوا",
  "Do Not Judge": "لا تدينوا",
  "Ask, Seek, Knock": "اسألوا، اطلبوا، اقرعوا",
  "The Narrow Gate": "الباب الضيق",
  "A Tree and Its Fruit": "الشجرة وثمرها",
  "Build Your House on the Rock": "ابنوا بيتكم على الصخر",
  "Jesus Heals a Leper": "يسوع يشفي أبرص",
  "The Centurion's Faith": "إيمان قائد المئة",
  "Jesus Heals Many": "يسوع يشفي كثيرين",
  "Jesus Calms the Storm": "يسوع يهدئ العاصفة",
  "Jesus Heals Two Demon-Possessed Men": "يسوع يشفي رجلين مجنونين",
  "The Parable of the Sower": "مَثَل الزارع",
  "The Parable of the Weeds": "مَثَل الزوان",
  "The Parables of the Mustard Seed and Leaven": "مَثَلا حبة الخردل والخميرة",
  "The Parables of Hidden Treasure and the Pearl": "مَثَلا الكنز المخفي واللؤلؤة",
  "The Death of John the Baptist": "موت يوحنا المعمدان",
  "Jesus Feeds Five Thousand": "يسوع يطعم خمسة آلاف",
  "Jesus Walks on Water": "يسوع يمشي على الماء",
  "Peter's Confession of Christ": "اعتراف بطرس بالمسيح",
  "Jesus Predicts His Death": "يسوع ينبئ بموته",
  "Take Up Your Cross": "احملوا صليبكم",
  "The Transfiguration": "التجلي",
  "Who Is the Greatest?": "من هو الأعظم؟",
  "The Parable of the Lost Sheep": "مَثَل الخروف الضال",
  "The Parable of the Unforgiving Servant": "مَثَل العبد الذي لا يغفر",
  "Teaching About Divorce": "تعليم عن الطلاق",
  "Jesus Blesses the Children": "يسوع يبارك الأطفال",
  "The Rich Young Man": "الشاب الغني",
  "The Parable of the Workers in the Vineyard": "مَثَل عمال الكرم",
  "Jesus Heals Two Blind Men": "يسوع يشفي أعميين",
  "The Triumphal Entry": "الدخول الانتصاري",
  "Jesus Cleanses the Temple": "يسوع يطهر الهيكل",
  "The Parable of the Wedding Feast": "مَثَل وليمة العرس",
  "Paying Taxes to Caesar": "دفع الجزية لقيصر",
  "The Greatest Commandment": "الوصية العظمى",
  "Jesus Foretells the Future": "يسوع ينبئ بالمستقبل",
  "No One Knows the Day or Hour": "لا أحد يعرف اليوم ولا الساعة",
  "The Parable of the Ten Virgins": "مَثَل العذارى العشر",
  "The Parable of the Talents": "مَثَل الوزنات",
  "The Final Judgment": "الدينونة الأخيرة",
  "The Plot to Kill Jesus": "المؤامرة لقتل يسوع",
  "The Last Supper": "العشاء الأخير",
  "Jesus Prays in Gethsemane": "يسوع يصلي في جثسيماني",
  "The Betrayal and Arrest of Jesus": "خيانة يسوع والقبض عليه",
  "Jesus Before the Council": "يسوع أمام المجمع",
  "Peter Denies Jesus": "بطرس ينكر يسوع",
  "Jesus Before Pilate": "يسوع أمام بيلاطس",
  "Jesus Is Mocked": "الاستهزاء بيسوع",
  "The Crucifixion": "الصلب",
  "The Burial of Jesus": "دفن يسوع",
  "The Resurrection": "القيامة",
  "The Great Commission": "الإرسالية العظمى",

  // ============ MARK ============
  "Jesus Drives Out an Unclean Spirit": "يسوع يطرد روحًا نجسًا",
  "Jesus Heals a Demon-Possessed Man": "يسوع يشفي رجلًا مجنونًا",
  "Jesus Heals a Woman and Raises a Girl": "يسوع يشفي امرأة ويقيم صبية",
  "Jesus Rejected at Nazareth": "رفض يسوع في الناصرة",
  "Blind Bartimaeus": "بارتيماوس الأعمى",

  // ============ LUKE ============
  "Introduction": "مقدمة",
  "The Birth of John the Baptist Foretold": "البشارة بولادة يوحنا المعمدان",
  "The Birth of Jesus Foretold": "البشارة بولادة يسوع",
  "Mary Visits Elizabeth": "مريم تزور أليصابات",
  "Mary's Song of Praise": "ترنيمة مريم",
  "The Birth of John the Baptist": "ولادة يوحنا المعمدان",
  "Zechariah's Prophecy": "نبوة زكريا",
  "The Birth of Jesus": "ولادة يسوع",
  "The Shepherds and the Angels": "الرعاة والملائكة",
  "Jesus Presented at the Temple": "تقديم يسوع في الهيكل",
  "The Boy Jesus at the Temple": "الصبي يسوع في الهيكل",
  "Jesus Sends Out the Seventy-Two": "يسوع يرسل الاثنين والسبعين",
  "The Parable of the Good Samaritan": "مَثَل السامري الصالح",
  "Jesus Visits Martha and Mary": "يسوع يزور مرثا ومريم",
  "The Parable of the Lost Coin": "مَثَل الدرهم المفقود",
  "The Parable of the Prodigal Son": "مَثَل الابن الضال",
  "Jesus Prays on the Mount of Olives": "يسوع يصلي على جبل الزيتون",
  "Jesus Before Pilate and Herod": "يسوع أمام بيلاطس وهيرودس",
  "The Death of Jesus": "موت يسوع",
  "On the Road to Emmaus": "على طريق عمواس",
  "Jesus Appears to His Disciples": "يسوع يظهر لتلاميذه",
  "The Ascension": "الصعود",

  // ============ JOHN ============
  "The Word Became Flesh": "الكلمة صار جسدًا",
  "The Testimony of John the Baptist": "شهادة يوحنا المعمدان",
  "Jesus Calls Philip and Nathanael": "يسوع يدعو فيلبس ونثنائيل",
  "The Wedding at Cana": "العرس في قانا",
  "Jesus and Nicodemus": "يسوع ونيقوديموس",
  "For God So Loved the World": "لأنه هكذا أحب الله العالم",
  "John the Baptist Exalts Christ": "يوحنا المعمدان يمجد المسيح",
  "Jesus and the Woman at the Well": "يسوع والمرأة السامرية",
  "Jesus Heals an Official's Son": "يسوع يشفي ابن أحد الرؤساء",
  "Jesus Heals at the Pool of Bethesda": "يسوع يشفي عند بركة بيت حسدا",
  "The Authority of the Son": "سلطان الابن",
  "Jesus the Bread of Life": "يسوع خبز الحياة",
  "Many Disciples Turn Away": "كثيرون من التلاميذ يرتدون",
  "Jesus at the Feast of Tabernacles": "يسوع في عيد المظال",
  "Rivers of Living Water": "أنهار ماء حي",
  "The Woman Caught in Adultery": "المرأة المضبوطة في زنا",
  "Jesus the Light of the World": "يسوع نور العالم",
  "The Truth Will Set You Free": "الحق يحرركم",
  "Jesus Heals a Man Born Blind": "يسوع يشفي رجلًا مولودًا أعمى",
  "Jesus the Good Shepherd": "يسوع الراعي الصالح",
  "Jesus at the Feast of Dedication": "يسوع في عيد التكريس",
  "The Death of Lazarus": "موت لعازر",
  "Jesus Comforts Martha and Mary": "يسوع يعزي مرثا ومريم",
  "Jesus Raises Lazarus": "يسوع يقيم لعازر",
  "Mary Anoints Jesus": "مريم تدهن يسوع بالطيب",
  "Jesus Washes the Disciples' Feet": "يسوع يغسل أرجل التلاميذ",
  "Jesus Predicts His Betrayal": "يسوع ينبئ بخيانته",
  "A New Commandment": "وصية جديدة",
  "Jesus Predicts Peter's Denial": "يسوع ينبئ بإنكار بطرس",
  "Jesus Comforts His Disciples": "يسوع يعزي تلاميذه",
  "I Am the Way, the Truth, and the Life": "أنا هو الطريق والحق والحياة",
  "The Promise of the Holy Spirit": "الوعد بالروح القدس",
  "I Am the True Vine": "أنا الكرمة الحقيقية",
  "The Greatest Love": "المحبة العظمى",
  "The World's Hatred": "بغضة العالم",
  "The Work of the Holy Spirit": "عمل الروح القدس",
  "Sorrow Will Turn to Joy": "الحزن يتحول إلى فرح",
  "Jesus Has Overcome the World": "يسوع قد غلب العالم",
  "Jesus Prays for Himself": "يسوع يصلي من أجل نفسه",
  "Jesus Prays for His Disciples": "يسوع يصلي من أجل تلاميذه",
  "Jesus Prays for All Believers": "يسوع يصلي من أجل جميع المؤمنين",
  "Jesus Before the High Priest": "يسوع أمام رئيس الكهنة",
  "Jesus Sentenced to Be Crucified": "الحكم على يسوع بالصلب",
  "The Empty Tomb": "القبر الفارغ",
  "Jesus Appears to Mary Magdalene": "يسوع يظهر لمريم المجدلية",
  "Jesus and Thomas": "يسوع وتوما",
  "Jesus Appears at the Sea of Galilee": "يسوع يظهر عند بحر الجليل",
  "Jesus Restores Peter": "يسوع يرد بطرس",

  // ============ ACTS ============
  "Matthias Chosen to Replace Judas": "اختيار متياس بديلًا ليهوذا",
  "The Day of Pentecost": "يوم الخمسين",
  "Peter's Sermon": "عظة بطرس",
  "The First Believers": "المؤمنون الأوائل",
  "The Fellowship of Believers": "شركة المؤمنين",
  "Peter Heals a Lame Man": "بطرس يشفي رجلًا أعرج",
  "Peter Speaks in Solomon's Portico": "بطرس يتكلم في رواق سليمان",
  "The Conversion of Saul": "اهتداء شاول",
  "Saul Begins to Preach": "شاول يبدأ الكرازة",
  "Peter and Cornelius": "بطرس وكرنيليوس",
  "Paul in Thessalonica and Berea": "بولس في تسالونيكي وبيرية",
  "Paul in Athens": "بولس في أثينا",

  // ============ ROMANS ============
  "Greetings from Paul": "تحيات من بولس",
  "The Righteous Shall Live by Faith": "البار بالإيمان يحيا",
  "God's Wrath Against Sin": "غضب الله على الخطية",
  "God's Faithfulness": "أمانة الله",
  "Righteousness Through Faith": "البر بالإيمان",
  "Peace with God Through Faith": "السلام مع الله بالإيمان",
  "Death Through Adam, Life Through Christ": "الموت بآدم والحياة بالمسيح",
  "Dead to Sin, Alive in Christ": "أموات عن الخطية أحياء في المسيح",
  "Slaves to Righteousness": "عبيد للبر",
  "The Struggle with Sin": "الصراع مع الخطية",
  "Life in the Spirit": "الحياة في الروح",
  "Future Glory": "المجد العتيد",
  "More Than Conquerors": "أكثر من غالبين",
  "Salvation for All Who Believe": "الخلاص لكل من يؤمن",
  "How Beautiful Are the Feet": "ما أجمل أقدام المبشرين",
  "A Living Sacrifice": "ذبيحة حية",
  "Marks of a True Christian": "صفات المسيحي الحقيقي",
  "Submission to Authorities": "الخضوع للسلطات",
  "Love Fulfills the Law": "المحبة تكميل الناموس",

  // ============ 1 CORINTHIANS ============
  "The Way of Love": "طريق المحبة",
  "The Resurrection of Christ": "قيامة المسيح",
  "The Resurrection Body": "جسد القيامة",
  "The Mystery of the Last Trumpet": "سر البوق الأخير",

  // ============ GALATIANS ============
  "Freedom in Christ": "الحرية في المسيح",
  "Walking by the Spirit": "السلوك بالروح",
  "The Fruit of the Spirit": "ثمر الروح",

  // ============ EPHESIANS ============
  "Made Alive in Christ": "أحياء في المسيح",
  "Unity in Christ": "الوحدة في المسيح",
  "Unity in the Body of Christ": "الوحدة في جسد المسيح",
  "The New Life": "الحياة الجديدة",
  "Children and Parents": "الأولاد والوالدون",
  "The Armor of God": "سلاح الله الكامل",

  // ============ PHILIPPIANS ============
  "Christ's Example of Humility": "مثال المسيح في التواضع",
  "Shining as Lights in the World": "أنيروا كأنوار في العالم",
  "Rejoice in the Lord Always": "افرحوا في الرب كل حين",
  "Do Not Be Anxious": "لا تهتموا بشيء",
  "God's Provision": "إعالة الله",

  // ============ HEBREWS ============
  "By Faith": "بالإيمان",
  "The Race of Faith": "سباق الإيمان",
  "God's Discipline": "تأديب الله",

  // ============ JAMES ============
  "Greeting": "تحية",
  "Testing of Your Faith": "امتحان إيمانكم",
  "Hearing and Doing the Word": "سماع الكلمة والعمل بها",
  "Do Not Show Favoritism": "لا تحابوا",
  "Faith and Works": "الإيمان والأعمال",
  "Taming the Tongue": "ترويض اللسان",

  // ============ 1 JOHN ============
  "Walking in the Light": "السلوك في النور",
  "Children of God": "أولاد الله",
  "Test the Spirits": "امتحنوا الأرواح",
  "God Is Love": "الله محبة",

  // ============ REVELATION ============
  "Prologue": "مقدمة",
  "Vision of the Son of Man": "رؤيا ابن الإنسان",
  "The Throne in Heaven": "العرش في السماء",
  "The Scroll and the Lamb": "الدرج والخروف",
  "A Great Multitude from Every Nation": "جمهور عظيم من كل أمة",
  "The Marriage Supper of the Lamb": "عشاء عرس الخروف",
  "The Rider on the White Horse": "الراكب على الفرس الأبيض",
  "The Thousand Years": "الألف سنة",
  "The Great White Throne Judgment": "دينونة العرش الأبيض العظيم",
  "A New Heaven and a New Earth": "سماء جديدة وأرض جديدة",
  "The New Jerusalem": "أورشليم الجديدة",
  "The River of Life": "نهر الحياة",
  "Jesus Is Coming Soon": "يسوع آتٍ سريعًا",
};
export default HEADINGS_AR;
