/** French translations of Bible section headings */
const HEADINGS_FR: Record<string, string> = {
  "The Creation of the World": "La Création du Monde",
  "The Fourth Day: Sun, Moon, and Stars": "Le Quatrième Jour : Soleil, Lune et Étoiles",
  "The Sixth Day: Land Animals and Humans": "Le Sixième Jour : Animaux Terrestres et Humains",
  "The Seventh Day: God Rests": "Le Septième Jour : Dieu se Repose",
  "The Garden of Eden": "Le Jardin d'Éden",
  "The Creation of Woman": "La Création de la Femme",
  "The Fall of Man": "La Chute de l'Homme",
  "God's Judgment": "Le Jugement de Dieu",
  "Banished from the Garden": "Chassés du Jardin",
  "Cain and Abel": "Caïn et Abel",
  "The Line of Cain": "La Descendance de Caïn",
  "Seth and Enosh": "Seth et Énosh",
  "From Adam to Noah": "D'Adam à Noé",
  "Wickedness in the World": "La Méchanceté dans le Monde",
  "Noah and the Ark": "Noé et l'Arche",
  "The Great Flood": "Le Déluge",
  "The Flood Recedes": "Le Retrait des Eaux",
  "God's Promise to Noah": "La Promesse de Dieu à Noé",
  "God's Covenant with Noah": "L'Alliance de Dieu avec Noé",
  "Noah's Sons": "Les Fils de Noé",
  "The Table of Nations": "La Table des Nations",
  "The Tower of Babel": "La Tour de Babel",
  "From Shem to Abram": "De Sem à Abram",
  "The Call of Abram": "L'Appel d'Abram",
  "Abram in Egypt": "Abram en Égypte",
  "God's Covenant with Abram": "L'Alliance de Dieu avec Abram",
  "The Covenant of Circumcision": "L'Alliance de la Circoncision",
  "The Promise of Isaac": "La Promesse d'Isaac",
  "Three Visitors": "Les Trois Visiteurs",
  "Abraham Pleads for Sodom": "Abraham Intercède pour Sodome",
  "The Destruction of Sodom and Gomorrah": "La Destruction de Sodome et Gomorrhe",
  "Lot's Daughters": "Les Filles de Lot",
  "The Birth of Isaac": "La Naissance d'Isaac",
  "Hagar and Ishmael Sent Away": "Le Renvoi d'Agar et d'Ismaël",
  "The Sacrifice of Isaac": "Le Sacrifice d'Isaac",
  "Isaac and Rebekah": "Isaac et Rébecca",
  "Jacob and Esau": "Jacob et Ésaü",
  "Esau Sells His Birthright": "Ésaü Vend son Droit d'Aînesse",
  "Jacob Steals Esau's Blessing": "Jacob Dérobe la Bénédiction d'Ésaü",
  "Jacob's Dream at Bethel": "Le Songe de Jacob à Béthel",
  "Jacob Wrestles with God": "Jacob Lutte avec Dieu",
  "Joseph's Dreams": "Les Songes de Joseph",
  "Joseph Sold by His Brothers": "Joseph Vendu par ses Frères",
  "Joseph in Potiphar's House": "Joseph dans la Maison de Potiphar",
  "Joseph Interprets Dreams in Prison": "Joseph Interprète des Songes en Prison",
  "Pharaoh's Dreams": "Les Songes de Pharaon",
  "Joseph Made Ruler of Egypt": "Joseph Gouverneur d'Égypte",
  "Joseph Reveals Himself to His Brothers": "Joseph se Fait Reconnaître par ses Frères",
  "The Death of Jacob": "La Mort de Jacob",
  "Joseph Reassures His Brothers": "Joseph Rassure ses Frères",
  "Israel Oppressed in Egypt": "Israël Opprimé en Égypte",
  "The Hebrew Midwives": "Les Sages-Femmes Hébreuses",
  "The Birth of Moses": "La Naissance de Moïse",
  "Moses Flees to Midian": "La Fuite de Moïse à Madian",
  "The Burning Bush": "Le Buisson Ardent",
  "The First Plague: Water to Blood": "La Première Plaie : l'Eau Changée en Sang",
  "The Passover": "La Pâque",
  "The Tenth Plague: Death of the Firstborn": "La Dixième Plaie : la Mort des Premiers-Nés",
  "Crossing the Red Sea": "La Traversée de la Mer Rouge",
  "The Ten Commandments": "Les Dix Commandements",
  "The Way of the Righteous and the Wicked": "La Voie du Juste et du Méchant",
  "The Lord Is My Shepherd": "L'Éternel Est Mon Berger",
  "A Prayer of Repentance": "Prière de Repentance",
  "Abiding in the Shadow of the Almighty": "À l'Abri du Tout-Puissant",
  "A Psalm of Thanksgiving": "Psaume d'Action de Grâces",
  "The Glories of God's Word": "Les Gloires de la Parole de Dieu",
  "Beth": "Beth",
  "Gimel": "Gimel",
  "Daleth": "Daleth",
  "He": "He",
  "Waw": "Waw",
  "Zayin": "Zayin",
  "Heth": "Heth",
  "Teth": "Teth",
  "Yodh": "Yodh",
  "Kaph": "Kaph",
  "Lamedh": "Lamedh",
  "Mem": "Mem",
  "Nun": "Nun",
  "Samekh": "Samekh",
  "Ayin": "Ayin",
  "Pe": "Pe",
  "Tsadhe": "Tsadhe",
  "Qoph": "Qoph",
  "Resh": "Resh",
  "Sin and Shin": "Sin et Shin",
  "Taw": "Taw",
  "God's Perfect Knowledge": "La Connaissance Parfaite de Dieu",
  "Praise the Lord!": "Louez l'Éternel !",
  "The Purpose of Proverbs": "Le But des Proverbes",
  "A Father's Instruction": "L'Instruction d'un Père",
  "Wisdom Calls Out": "La Sagesse Élève sa Voix",
  "Trust in the Lord": "Confie-toi en l'Éternel",
  "The Value of Wisdom": "La Valeur de la Sagesse",
  "The Words of King Lemuel": "Les Paroles du Roi Lemuel",
  "The Virtuous Woman": "La Femme Vertueuse",
  "Isaiah's Vision of the Lord": "La Vision d'Ésaïe du Seigneur",
  "The Sign of Immanuel": "Le Signe d'Emmanuel",
  "A Child Is Born": "Un Enfant Nous Est Né",
  "Comfort for God's People": "Consolation pour le Peuple de Dieu",
  "The Everlasting God": "Le Dieu Éternel",
  "The Suffering Servant": "Le Serviteur Souffrant",
  "An Invitation to the Thirsty": "Invitation aux Assoiffés",
  "The Genealogy of Jesus": "La Généalogie de Jésus",
  "The Birth of Jesus Christ": "La Naissance de Jésus-Christ",
  "The Visit of the Wise Men": "La Visite des Mages",
  "The Flight to Egypt": "La Fuite en Égypte",
  "Herod Kills the Children": "Hérode Fait Massacrer les Enfants",
  "John the Baptist Prepares the Way": "Jean-Baptiste Prépare le Chemin",
  "The Baptism of Jesus": "Le Baptême de Jésus",
  "The Temptation of Jesus": "La Tentation de Jésus",
  "Jesus Begins His Ministry": "Jésus Commence son Ministère",
  "Jesus Calls His First Disciples": "Jésus Appelle ses Premiers Disciples",
  "The Sermon on the Mount": "Le Sermon sur la Montagne",
  "The Beatitudes": "Les Béatitudes",
  "Salt and Light": "Le Sel et la Lumière",
  "Christ Fulfills the Law": "Christ Accomplit la Loi",
  "Teaching About Anger": "Enseignement sur la Colère",
  "Teaching About Lust": "Enseignement sur la Convoitise",
  "Teaching About Oaths": "Enseignement sur les Serments",
  "Teaching About Retaliation": "Enseignement sur la Vengeance",
  "Love Your Enemies": "Aimez vos Ennemis",
  "Teaching About Giving": "Enseignement sur l'Aumône",
  "Teaching About Prayer": "Enseignement sur la Prière",
  "The Lord's Prayer": "La Prière du Seigneur",
  "Teaching About Fasting": "Enseignement sur le Jeûne",
  "Treasures in Heaven": "Les Trésors dans le Ciel",
  "Do Not Worry": "Ne vous Inquiétez pas",
  "Do Not Judge": "Ne Jugez pas",
  "Ask, Seek, Knock": "Demandez, Cherchez, Frappez",
  "The Narrow Gate": "La Porte Étroite",
  "A Tree and Its Fruit": "L'Arbre et ses Fruits",
  "Build Your House on the Rock": "Construire sa Maison sur le Roc",
  "Jesus Heals a Leper": "Jésus Guérit un Lépreux",
  "The Centurion's Faith": "La Foi du Centurion",
  "Jesus Heals Many": "Jésus Guérit de Nombreux Malades",
  "Jesus Calms the Storm": "Jésus Apaise la Tempête",
  "Jesus Heals Two Demon-Possessed Men": "Jésus Guérit Deux Démoniaques",
  "The Parable of the Sower": "La Parabole du Semeur",
  "The Parable of the Weeds": "La Parabole de l'Ivraie",
  "The Parables of the Mustard Seed and Leaven": "Les Paraboles du Grain de Moutarde et du Levain",
  "The Parables of Hidden Treasure and the Pearl": "Les Paraboles du Trésor Caché et de la Perle",
  "The Death of John the Baptist": "La Mort de Jean-Baptiste",
  "Jesus Feeds Five Thousand": "Jésus Nourrit Cinq Mille Hommes",
  "Jesus Walks on Water": "Jésus Marche sur les Eaux",
  "Peter's Confession of Christ": "La Confession de Pierre",
  "Jesus Predicts His Death": "Jésus Annonce sa Mort",
  "Take Up Your Cross": "Prenez votre Croix",
  "The Transfiguration": "La Transfiguration",
  "Who Is the Greatest?": "Qui Est le Plus Grand ?",
  "The Parable of the Lost Sheep": "La Parabole de la Brebis Perdue",
  "The Parable of the Unforgiving Servant": "La Parabole du Serviteur Impitoyable",
  "Teaching About Divorce": "Enseignement sur le Divorce",
  "Jesus Blesses the Children": "Jésus Bénit les Enfants",
  "The Rich Young Man": "Le Jeune Homme Riche",
  "The Parable of the Workers in the Vineyard": "La Parabole des Ouvriers de la Vigne",
  "Jesus Heals Two Blind Men": "Jésus Guérit Deux Aveugles",
  "The Triumphal Entry": "L'Entrée Triomphale",
  "Jesus Cleanses the Temple": "Jésus Purifie le Temple",
  "The Parable of the Wedding Feast": "La Parabole du Festin de Noces",
  "Paying Taxes to Caesar": "L'Impôt dû à César",
  "The Greatest Commandment": "Le Plus Grand Commandement",
  "Jesus Foretells the Future": "Jésus Annonce l'Avenir",
  "No One Knows the Day or Hour": "Nul ne Connaît le Jour ni l'Heure",
  "The Parable of the Ten Virgins": "La Parabole des Dix Vierges",
  "The Parable of the Talents": "La Parabole des Talents",
  "The Final Judgment": "Le Jugement Dernier",
  "The Plot to Kill Jesus": "Le Complot contre Jésus",
  "The Last Supper": "La Cène",
  "Jesus Prays in Gethsemane": "Jésus Prie à Gethsémané",
  "The Betrayal and Arrest of Jesus": "La Trahison et l'Arrestation de Jésus",
  "Jesus Before the Council": "Jésus devant le Sanhédrin",
  "Peter Denies Jesus": "Le Reniement de Pierre",
  "Jesus Before Pilate": "Jésus devant Pilate",
  "Jesus Is Mocked": "Les Outrages contre Jésus",
  "The Crucifixion": "La Crucifixion",
  "The Burial of Jesus": "La Sépulture de Jésus",
  "The Resurrection": "La Résurrection",
  "The Great Commission": "Le Grand Ordre Missionnaire",
  "Jesus Drives Out an Unclean Spirit": "Jésus Chasse un Esprit Impur",
  "Jesus Heals a Demon-Possessed Man": "Jésus Guérit un Démoniaque",
  "Jesus Heals a Woman and Raises a Girl": "Jésus Guérit une Femme et Ressuscite une Jeune Fille",
  "Jesus Rejected at Nazareth": "Jésus Rejeté à Nazareth",
  "Blind Bartimaeus": "L'Aveugle Bartimée",
  "Jesus Before Pilate and Herod": "Jésus devant Pilate et Hérode",
  "The Death of Jesus": "La Mort de Jésus",
  "On the Road to Emmaus": "Sur le Chemin d'Emmaüs",
  "Jesus Appears to His Disciples": "Jésus Apparaît à ses Disciples",
  "The Ascension": "L'Ascension",
  "Introduction": "Introduction",
  "The Birth of John the Baptist Foretold": "L'Annonce de la Naissance de Jean-Baptiste",
  "The Birth of Jesus Foretold": "L'Annonce de la Naissance de Jésus",
  "Mary Visits Elizabeth": "Marie Rend Visite à Élisabeth",
  "Mary's Song of Praise": "Le Cantique de Marie",
  "The Birth of John the Baptist": "La Naissance de Jean-Baptiste",
  "Zechariah's Prophecy": "La Prophétie de Zacharie",
  "The Birth of Jesus": "La Naissance de Jésus",
  "The Shepherds and the Angels": "Les Bergers et les Anges",
  "Jesus Presented at the Temple": "Jésus Présenté au Temple",
  "The Boy Jesus at the Temple": "L'Enfant Jésus au Temple",
  "Jesus Sends Out the Seventy-Two": "Jésus Envoie les Soixante-Douze",
  "The Parable of the Good Samaritan": "La Parabole du Bon Samaritain",
  "Jesus Visits Martha and Mary": "Jésus chez Marthe et Marie",
  "The Parable of the Lost Coin": "La Parabole de la Pièce Perdue",
  "The Parable of the Prodigal Son": "La Parabole du Fils Prodigue",
  "Jesus Prays on the Mount of Olives": "Jésus Prie sur le Mont des Oliviers",
  "The Empty Tomb": "Le Tombeau Vide",
  "Jesus Appears to Mary Magdalene": "Jésus Apparaît à Marie-Madeleine",
  "Jesus and Thomas": "Jésus et Thomas",
  "The Word Became Flesh": "La Parole Faite Chair",
  "The Testimony of John the Baptist": "Le Témoignage de Jean-Baptiste",
  "Jesus Calls Philip and Nathanael": "Jésus Appelle Philippe et Nathanaël",
  "The Wedding at Cana": "Les Noces de Cana",
  "Jesus and Nicodemus": "Jésus et Nicodème",
  "For God So Loved the World": "Car Dieu a tant Aimé le Monde",
  "John the Baptist Exalts Christ": "Jean-Baptiste Rend Témoignage au Christ",
  "Jesus and the Woman at the Well": "Jésus et la Samaritaine",
  "Jesus Heals an Official's Son": "Jésus Guérit le Fils d'un Officier",
  "Jesus Heals at the Pool of Bethesda": "Jésus Guérit à la Piscine de Béthesda",
  "The Authority of the Son": "L'Autorité du Fils",
  "Jesus the Bread of Life": "Jésus, le Pain de Vie",
  "Many Disciples Turn Away": "Beaucoup de Disciples se Retirent",
  "Jesus at the Feast of Tabernacles": "Jésus à la Fête des Tabernacles",
  "Rivers of Living Water": "Des Fleuves d'Eau Vive",
  "The Woman Caught in Adultery": "La Femme Adultère",
  "Jesus the Light of the World": "Jésus, la Lumière du Monde",
  "The Truth Will Set You Free": "La Vérité Vous Rendra Libres",
  "Jesus Heals a Man Born Blind": "Jésus Guérit un Aveugle-Né",
  "Jesus the Good Shepherd": "Jésus, le Bon Berger",
  "Jesus at the Feast of Dedication": "Jésus à la Fête de la Dédicace",
  "The Death of Lazarus": "La Mort de Lazare",
  "Jesus Comforts Martha and Mary": "Jésus Console Marthe et Marie",
  "Jesus Raises Lazarus": "Jésus Ressuscite Lazare",
  "Mary Anoints Jesus": "Marie Oint Jésus",
  "Jesus Washes the Disciples' Feet": "Jésus Lave les Pieds de ses Disciples",
  "Jesus Predicts His Betrayal": "Jésus Annonce sa Trahison",
  "A New Commandment": "Un Commandement Nouveau",
  "Jesus Predicts Peter's Denial": "Jésus Annonce le Reniement de Pierre",
  "Jesus Comforts His Disciples": "Jésus Console ses Disciples",
  "I Am the Way, the Truth, and the Life": "Je Suis le Chemin, la Vérité et la Vie",
  "The Promise of the Holy Spirit": "La Promesse du Saint-Esprit",
  "I Am the True Vine": "Je Suis le Vrai Cep",
  "The Greatest Love": "Le Plus Grand Amour",
  "The World's Hatred": "La Haine du Monde",
  "The Work of the Holy Spirit": "L'Œuvre du Saint-Esprit",
  "Sorrow Will Turn to Joy": "La Tristesse Changée en Joie",
  "Jesus Has Overcome the World": "Jésus a Vaincu le Monde",
  "Jesus Prays for Himself": "Jésus Prie pour Lui-même",
  "Jesus Prays for His Disciples": "Jésus Prie pour ses Disciples",
  "Jesus Prays for All Believers": "Jésus Prie pour Tous les Croyants",
  "Jesus Before the High Priest": "Jésus devant le Souverain Sacrificateur",
  "Jesus Sentenced to Be Crucified": "Jésus Condamné à Être Crucifié",
  "Jesus Appears at the Sea of Galilee": "Jésus Apparaît au Bord de la Mer de Galilée",
  "Jesus Restores Peter": "Jésus Rétablit Pierre",
  "Matthias Chosen to Replace Judas": "Matthias Choisi pour Remplacer Judas",
  "The Day of Pentecost": "Le Jour de la Pentecôte",
  "Peter's Sermon": "Le Discours de Pierre",
  "The First Believers": "Les Premiers Croyants",
  "The Fellowship of Believers": "La Communion des Croyants",
  "Peter Heals a Lame Man": "Pierre Guérit un Boiteux",
  "Peter Speaks in Solomon's Portico": "Pierre Parle sous le Portique de Salomon",
  "The Conversion of Saul": "La Conversion de Saul",
  "Saul Begins to Preach": "Saul Commence à Prêcher",
  "Peter and Cornelius": "Pierre et Corneille",
  "Paul in Thessalonica and Berea": "Paul à Thessalonique et à Bérée",
  "Paul in Athens": "Paul à Athènes",
  "Greetings from Paul": "Salutations de Paul",
  "The Righteous Shall Live by Faith": "Le Juste Vivra par la Foi",
  "God's Wrath Against Sin": "La Colère de Dieu contre le Péché",
  "God's Faithfulness": "La Fidélité de Dieu",
  "Righteousness Through Faith": "La Justice par la Foi",
  "Peace with God Through Faith": "La Paix avec Dieu par la Foi",
  "Death Through Adam, Life Through Christ": "La Mort par Adam, la Vie par Christ",
  "Dead to Sin, Alive in Christ": "Morts au Péché, Vivants en Christ",
  "Slaves to Righteousness": "Esclaves de la Justice",
  "The Struggle with Sin": "Le Combat contre le Péché",
  "Life in the Spirit": "La Vie selon l'Esprit",
  "Future Glory": "La Gloire à Venir",
  "More Than Conquerors": "Plus que Vainqueurs",
  "Salvation for All Who Believe": "Le Salut pour Tous Ceux qui Croient",
  "How Beautiful Are the Feet": "Qu'ils Sont Beaux les Pieds",
  "A Living Sacrifice": "Un Sacrifice Vivant",
  "Marks of a True Christian": "Les Marques du Vrai Chrétien",
  "Submission to Authorities": "La Soumission aux Autorités",
  "Love Fulfills the Law": "L'Amour, Accomplissement de la Loi",
  "The Way of Love": "La Voie de l'Amour",
  "The Resurrection of Christ": "La Résurrection de Christ",
  "The Resurrection Body": "Le Corps de Résurrection",
  "The Mystery of the Last Trumpet": "Le Mystère de la Dernière Trompette",
  "Freedom in Christ": "La Liberté en Christ",
  "Walking by the Spirit": "Marcher selon l'Esprit",
  "The Fruit of the Spirit": "Le Fruit de l'Esprit",
  "Made Alive in Christ": "Rendus Vivants en Christ",
  "Unity in Christ": "L'Unité en Christ",
  "Unity in the Body of Christ": "L'Unité dans le Corps de Christ",
  "The New Life": "La Vie Nouvelle",
  "Children and Parents": "Enfants et Parents",
  "The Armor of God": "L'Armure de Dieu",
  "Christ's Example of Humility": "L'Exemple d'Humilité de Christ",
  "Shining as Lights in the World": "Briller comme des Flambeaux dans le Monde",
  "Rejoice in the Lord Always": "Réjouissez-vous en le Seigneur en Tout Temps",
  "Do Not Be Anxious": "Ne Soyez Inquiets de Rien",
  "God's Provision": "La Providence de Dieu",
  "By Faith": "Par la Foi",
  "The Race of Faith": "La Course de la Foi",
  "God's Discipline": "La Discipline de Dieu",
  "Greeting": "Salutation",
  "Testing of Your Faith": "L'Épreuve de la Foi",
  "Hearing and Doing the Word": "Écouter et Mettre en Pratique la Parole",
  "Do Not Show Favoritism": "Ne Faites pas de Favoritisme",
  "Faith and Works": "La Foi et les Œuvres",
  "Taming the Tongue": "Dompter la Langue",
  "Walking in the Light": "Marcher dans la Lumière",
  "Children of God": "Enfants de Dieu",
  "Test the Spirits": "Éprouvez les Esprits",
  "God Is Love": "Dieu Est Amour",
  "Prologue": "Prologue",
  "Vision of the Son of Man": "Vision du Fils de l'Homme",
  "The Throne in Heaven": "Le Trône dans le Ciel",
  "The Scroll and the Lamb": "Le Rouleau et l'Agneau",
  "A Great Multitude from Every Nation": "Une Grande Foule de Toute Nation",
  "The Marriage Supper of the Lamb": "Le Festin des Noces de l'Agneau",
  "The Rider on the White Horse": "Le Cavalier sur le Cheval Blanc",
  "The Thousand Years": "Les Mille Ans",
  "The Great White Throne Judgment": "Le Jugement du Grand Trône Blanc",
  "A New Heaven and a New Earth": "Un Nouveau Ciel et une Nouvelle Terre",
  "The New Jerusalem": "La Nouvelle Jérusalem",
  "The River of Life": "Le Fleuve de la Vie",
  "Jesus Is Coming Soon": "Jésus Vient Bientôt",
};
export default HEADINGS_FR;
