/** German translations of Bible section headings */
const HEADINGS_DE: Record<string, string> = {
  "A Child Is Born": "Ein Kind ist uns geboren",
  "A Father's Instruction": "Die Unterweisung eines Vaters",
  "A Great Multitude from Every Nation": "Eine große Schar aus allen Völkern",
  "A Living Sacrifice": "Ein lebendiges Opfer",
  "A New Commandment": "Ein neues Gebot",
  "A New Heaven and a New Earth": "Ein neuer Himmel und eine neue Erde",
  "A Prayer of Repentance": "Ein Gebet der Buße",
  "A Psalm of Thanksgiving": "Ein Psalm des Dankes",
  "A Tree and Its Fruit": "Der Baum und seine Frucht",
  "Abiding in the Shadow of the Almighty": "Im Schatten des Allmächtigen",
  "Abraham Pleads for Sodom": "Abraham bittet für Sodom",
  "Abram in Egypt": "Abram in Ägypten",
  "An Invitation to the Thirsty": "Einladung an die Durstigen",
  "Ask, Seek, Knock": "Bittet, sucht, klopft an",
  "Ayin": "Ayin",
  "Banished from the Garden": "Vertreibung aus dem Garten",
  "Beth": "Beth",
  "Blind Bartimaeus": "Der blinde Bartimäus",
  "Build Your House on the Rock": "Das Haus auf dem Felsen",
  "By Faith": "Durch den Glauben",
  "Cain and Abel": "Kain und Abel",
  "Children and Parents": "Kinder und Eltern",
  "Children of God": "Kinder Gottes",
  "Christ Fulfills the Law": "Christus erfüllt das Gesetz",
  "Christ's Example of Humility": "Christi Vorbild der Demut",
  "Comfort for God's People": "Trost für Gottes Volk",
  "Crossing the Red Sea": "Der Durchzug durch das Rote Meer",
  "Daleth": "Daleth",
  "Dead to Sin, Alive in Christ": "Tot für die Sünde, lebendig in Christus",
  "Death Through Adam, Life Through Christ": "Tod durch Adam, Leben durch Christus",
  "Do Not Be Anxious": "Sorgt euch nicht",
  "Do Not Judge": "Richtet nicht",
  "Do Not Show Favoritism": "Warnung vor dem Ansehen der Person",
  "Do Not Worry": "Sorgt euch nicht",
  "Esau Sells His Birthright": "Esau verkauft sein Erstgeburtsrecht",
  "Faith and Works": "Glaube und Werke",
  "For God So Loved the World": "Denn so hat Gott die Welt geliebt",
  "Freedom in Christ": "Freiheit in Christus",
  "From Adam to Noah": "Von Adam bis Noah",
  "From Shem to Abram": "Von Sem bis Abram",
  "Future Glory": "Die zukünftige Herrlichkeit",
  "Gimel": "Gimel",
  "God Is Love": "Gott ist Liebe",
  "God's Covenant with Abram": "Gottes Bund mit Abram",
  "God's Covenant with Noah": "Gottes Bund mit Noah",
  "God's Discipline": "Gottes Züchtigung",
  "God's Faithfulness": "Gottes Treue",
  "God's Judgment": "Gottes Gericht",
  "God's Perfect Knowledge": "Gottes vollkommenes Wissen",
  "God's Promise to Noah": "Gottes Verheißung an Noah",
  "God's Provision": "Gottes Fürsorge",
  "God's Wrath Against Sin": "Gottes Zorn über die Sünde",
  "Greeting": "Gruß",
  "Greetings from Paul": "Grüße von Paulus",
  "Hagar and Ishmael Sent Away": "Hagar und Ismael werden weggeschickt",
  "He": "He",
  "Hearing and Doing the Word": "Hörer und Täter des Wortes",
  "Herod Kills the Children": "Der Kindermord des Herodes",
  "Heth": "Heth",
  "How Beautiful Are the Feet": "Wie lieblich sind die Füße",
  "I Am the True Vine": "Ich bin der wahre Weinstock",
  "I Am the Way, the Truth, and the Life": "Ich bin der Weg, die Wahrheit und das Leben",
  "Introduction": "Einleitung",
  "Isaac and Rebekah": "Isaak und Rebekka",
  "Isaiah's Vision of the Lord": "Jesajas Berufungsvision",
  "Israel Oppressed in Egypt": "Israels Unterdrückung in Ägypten",
  "Jacob and Esau": "Jakob und Esau",
  "Jacob Steals Esau's Blessing": "Jakob erschleicht Esaus Segen",
  "Jacob Wrestles with God": "Jakobs Kampf mit Gott",
  "Jacob's Dream at Bethel": "Jakobs Traum in Bethel",
  "Jesus and Nicodemus": "Jesus und Nikodemus",
  "Jesus and the Woman at the Well": "Jesus und die Samariterin am Brunnen",
  "Jesus and Thomas": "Jesus und Thomas",
  "Jesus Appears at the Sea of Galilee": "Jesus erscheint am See von Tiberias",
  "Jesus Appears to His Disciples": "Jesus erscheint seinen Jüngern",
  "Jesus Appears to Mary Magdalene": "Jesus erscheint Maria Magdalena",
  "Jesus Before Pilate": "Jesus vor Pilatus",
  "Jesus Before Pilate and Herod": "Jesus vor Pilatus und Herodes",
  "Jesus Before the Council": "Jesus vor dem Hohen Rat",
  "Jesus Before the High Priest": "Jesus vor dem Hohenpriester",
  "Jesus Begins His Ministry": "Der Beginn von Jesu Wirken",
  "Jesus Blesses the Children": "Jesus segnet die Kinder",
  "Jesus Calls His First Disciples": "Die Berufung der ersten Jünger",
  "Jesus Calls Philip and Nathanael": "Jesus beruft Philippus und Nathanael",
  "Jesus Calms the Storm": "Jesus stillt den Sturm",
  "Jesus Cleanses the Temple": "Die Tempelreinigung",
  "Jesus Comforts His Disciples": "Jesus tröstet seine Jünger",
  "Jesus Comforts Martha and Mary": "Jesus tröstet Martha und Maria",
  "Jesus Drives Out an Unclean Spirit": "Jesus treibt einen unreinen Geist aus",
  "Jesus Feeds Five Thousand": "Die Speisung der Fünftausend",
  "Jesus Foretells the Future": "Jesu Rede über die Endzeit",
  "Jesus Has Overcome the World": "Jesus hat die Welt überwunden",
  "Jesus Heals a Demon-Possessed Man": "Jesus heilt einen Besessenen",
  "Jesus Heals a Leper": "Jesus heilt einen Aussätzigen",
  "Jesus Heals a Man Born Blind": "Jesus heilt einen Blindgeborenen",
  "Jesus Heals a Woman and Raises a Girl": "Jesus heilt eine Frau und erweckt ein Mädchen",
  "Jesus Heals an Official's Son": "Jesus heilt den Sohn eines königlichen Beamten",
  "Jesus Heals at the Pool of Bethesda": "Jesus heilt am Teich Betesda",
  "Jesus Heals Many": "Jesus heilt viele Kranke",
  "Jesus Heals Two Blind Men": "Jesus heilt zwei Blinde",
  "Jesus Heals Two Demon-Possessed Men": "Jesus heilt zwei Besessene",
  "Jesus Is Coming Soon": "Jesus kommt bald",
  "Jesus Is Mocked": "Die Verspottung Jesu",
  "Jesus Predicts His Betrayal": "Jesus sagt seinen Verrat voraus",
  "Jesus Predicts His Death": "Jesus kündigt seinen Tod an",
  "Jesus Predicts Peter's Denial": "Jesus sagt die Verleugnung des Petrus voraus",
  "Jesus Presented at the Temple": "Jesu Darstellung im Tempel",
  "Jesus Prays for All Believers": "Jesus betet für alle Glaubenden",
  "Jesus Prays for Himself": "Jesus betet für sich selbst",
  "Jesus Prays for His Disciples": "Jesus betet für seine Jünger",
  "Jesus Prays in Gethsemane": "Jesus betet in Gethsemane",
  "Jesus Prays on the Mount of Olives": "Jesus betet auf dem Ölberg",
  "Jesus Raises Lazarus": "Die Auferweckung des Lazarus",
  "Jesus Rejected at Nazareth": "Die Ablehnung Jesu in Nazareth",
  "Jesus Restores Peter": "Jesus und die Wiederherstellung des Petrus",
  "Jesus Sends Out the Seventy-Two": "Jesus sendet die Zweiundsiebzig aus",
  "Jesus Sentenced to Be Crucified": "Jesus wird zum Tod verurteilt",
  "Jesus Visits Martha and Mary": "Jesus bei Martha und Maria",
  "Jesus Walks on Water": "Jesus geht auf dem Wasser",
  "Jesus Washes the Disciples' Feet": "Die Fußwaschung",
  "Jesus at the Feast of Dedication": "Jesus beim Tempelweihfest",
  "Jesus at the Feast of Tabernacles": "Jesus beim Laubhüttenfest",
  "Jesus the Bread of Life": "Jesus, das Brot des Lebens",
  "Jesus the Good Shepherd": "Jesus, der gute Hirte",
  "Jesus the Light of the World": "Jesus, das Licht der Welt",
  "John the Baptist Exalts Christ": "Johannes der Täufer bezeugt Christus",
  "John the Baptist Prepares the Way": "Johannes der Täufer bereitet den Weg",
  "Joseph Interprets Dreams in Prison": "Josef deutet Träume im Gefängnis",
  "Joseph Made Ruler of Egypt": "Josef wird Herrscher über Ägypten",
  "Joseph Reassures His Brothers": "Josef beruhigt seine Brüder",
  "Joseph Reveals Himself to His Brothers": "Josef gibt sich seinen Brüdern zu erkennen",
  "Joseph Sold by His Brothers": "Josef wird von seinen Brüdern verkauft",
  "Joseph in Potiphar's House": "Josef im Haus Potifars",
  "Joseph's Dreams": "Josefs Träume",
  "Kaph": "Kaph",
  "Lamedh": "Lamedh",
  "Life in the Spirit": "Leben im Geist",
  "Lot's Daughters": "Lots Töchter",
  "Love Fulfills the Law": "Die Liebe als Erfüllung des Gesetzes",
  "Love Your Enemies": "Von der Feindesliebe",
  "Made Alive in Christ": "Lebendig gemacht in Christus",
  "Many Disciples Turn Away": "Viele Jünger wenden sich ab",
  "Marks of a True Christian": "Kennzeichen eines wahren Christen",
  "Mary Anoints Jesus": "Maria salbt Jesus",
  "Mary Visits Elizabeth": "Maria besucht Elisabeth",
  "Mary's Song of Praise": "Marias Lobgesang",
  "Matthias Chosen to Replace Judas": "Die Nachwahl des Matthias",
  "Mem": "Mem",
  "More Than Conquerors": "Mehr als Überwinder",
  "Moses Flees to Midian": "Mose flieht nach Midian",
  "No One Knows the Day or Hour": "Niemand kennt den Tag oder die Stunde",
  "Noah and the Ark": "Noah und die Arche",
  "Noah's Sons": "Noahs Söhne",
  "Nun": "Nun",
  "On the Road to Emmaus": "Auf dem Weg nach Emmaus",
  "Paul in Athens": "Paulus in Athen",
  "Paul in Thessalonica and Berea": "Paulus in Thessalonich und Beröa",
  "Paying Taxes to Caesar": "Die Frage nach der Steuer",
  "Pe": "Pe",
  "Peace with God Through Faith": "Friede mit Gott durch den Glauben",
  "Peter Denies Jesus": "Die Verleugnung des Petrus",
  "Peter Heals a Lame Man": "Petrus heilt einen Gelähmten",
  "Peter Speaks in Solomon's Portico": "Die Rede des Petrus in der Halle Salomos",
  "Peter and Cornelius": "Petrus und Kornelius",
  "Peter's Confession of Christ": "Das Bekenntnis des Petrus",
  "Peter's Sermon": "Die Pfingstpredigt des Petrus",
  "Pharaoh's Dreams": "Die Träume des Pharao",
  "Praise the Lord!": "Lobet den Herrn!",
  "Prologue": "Prolog",
  "Qoph": "Qoph",
  "Rejoice in the Lord Always": "Freuet euch in dem Herrn allezeit",
  "Resh": "Resh",
  "Righteousness Through Faith": "Gerechtigkeit durch den Glauben",
  "Rivers of Living Water": "Ströme lebendigen Wassers",
  "Salt and Light": "Salz und Licht",
  "Salvation for All Who Believe": "Heil für alle, die glauben",
  "Samekh": "Samekh",
  "Saul Begins to Preach": "Saulus beginnt zu predigen",
  "Seth and Enosh": "Set und Enosch",
  "Shining as Lights in the World": "Leuchten in der Welt",
  "Sin and Shin": "Sin und Schin",
  "Slaves to Righteousness": "Knechte der Gerechtigkeit",
  "Sorrow Will Turn to Joy": "Trauer wird sich in Freude verwandeln",
  "Submission to Authorities": "Unterordnung unter die Obrigkeit",
  "Take Up Your Cross": "Nimm dein Kreuz auf dich",
  "Taming the Tongue": "Die Zähmung der Zunge",
  "Taw": "Taw",
  "Teaching About Anger": "Vom Zorn",
  "Teaching About Divorce": "Von der Ehescheidung",
  "Teaching About Fasting": "Vom Fasten",
  "Teaching About Giving": "Vom Almosengeben",
  "Teaching About Lust": "Von der Begierde",
  "Teaching About Oaths": "Vom Schwören",
  "Teaching About Prayer": "Vom Beten",
  "Teaching About Retaliation": "Von der Vergeltung",
  "Test the Spirits": "Die Prüfung der Geister",
  "Testing of Your Faith": "Bewährung des Glaubens",
  "Teth": "Teth",
  "The Armor of God": "Die Waffenrüstung Gottes",
  "The Ascension": "Die Himmelfahrt",
  "The Authority of the Son": "Die Vollmacht des Sohnes",
  "The Baptism of Jesus": "Die Taufe Jesu",
  "The Beatitudes": "Die Seligpreisungen",
  "The Betrayal and Arrest of Jesus": "Verrat und Gefangennahme Jesu",
  "The Birth of Isaac": "Die Geburt Isaaks",
  "The Birth of Jesus": "Die Geburt Jesu",
  "The Birth of Jesus Christ": "Die Geburt Jesu Christi",
  "The Birth of Jesus Foretold": "Die Ankündigung der Geburt Jesu",
  "The Birth of John the Baptist": "Die Geburt Johannes des Täufers",
  "The Birth of John the Baptist Foretold": "Die Ankündigung der Geburt Johannes des Täufers",
  "The Birth of Moses": "Die Geburt Moses",
  "The Boy Jesus at the Temple": "Der zwölfjährige Jesus im Tempel",
  "The Burial of Jesus": "Das Begräbnis Jesu",
  "The Burning Bush": "Der brennende Dornbusch",
  "The Call of Abram": "Die Berufung Abrams",
  "The Centurion's Faith": "Der Glaube des Hauptmanns",
  "The Conversion of Saul": "Die Bekehrung des Saulus",
  "The Covenant of Circumcision": "Der Bund der Beschneidung",
  "The Creation of Woman": "Die Erschaffung der Frau",
  "The Creation of the World": "Die Erschaffung der Welt",
  "The Crucifixion": "Die Kreuzigung",
  "The Day of Pentecost": "Das Pfingstwunder",
  "The Death of Jacob": "Der Tod Jakobs",
  "The Death of Jesus": "Der Tod Jesu",
  "The Death of John the Baptist": "Der Tod Johannes des Täufers",
  "The Death of Lazarus": "Der Tod des Lazarus",
  "The Destruction of Sodom and Gomorrah": "Die Zerstörung von Sodom und Gomorra",
  "The Empty Tomb": "Das leere Grab",
  "The Everlasting God": "Der ewige Gott",
  "The Fall of Man": "Der Sündenfall",
  "The Fellowship of Believers": "Die Gemeinschaft der Gläubigen",
  "The Final Judgment": "Das Endgericht",
  "The First Believers": "Die ersten Gläubigen",
  "The First Plague: Water to Blood": "Die erste Plage: Wasser wird zu Blut",
  "The Flight to Egypt": "Die Flucht nach Ägypten",
  "The Flood Recedes": "Die Flut geht zurück",
  "The Fourth Day: Sun, Moon, and Stars": "Der vierte Tag: Sonne, Mond und Sterne",
  "The Fruit of the Spirit": "Die Frucht des Geistes",
  "The Garden of Eden": "Der Garten Eden",
  "The Genealogy of Jesus": "Der Stammbaum Jesu",
  "The Glories of God's Word": "Die Herrlichkeit des Wortes Gottes",
  "The Great Commission": "Der Missionsbefehl",
  "The Great Flood": "Die große Flut",
  "The Great White Throne Judgment": "Das Gericht vor dem großen weißen Thron",
  "The Greatest Commandment": "Das höchste Gebot",
  "The Greatest Love": "Die größte Liebe",
  "The Hebrew Midwives": "Die hebräischen Hebammen",
  "The Last Supper": "Das letzte Abendmahl",
  "The Line of Cain": "Die Nachkommen Kains",
  "The Lord Is My Shepherd": "Der Herr ist mein Hirte",
  "The Lord's Prayer": "Das Vaterunser",
  "The Marriage Supper of the Lamb": "Das Hochzeitsmahl des Lammes",
  "The Mystery of the Last Trumpet": "Das Geheimnis der letzten Posaune",
  "The Narrow Gate": "Die enge Pforte",
  "The New Jerusalem": "Das neue Jerusalem",
  "The New Life": "Das neue Leben",
  "The Parable of the Good Samaritan": "Das Gleichnis vom barmherzigen Samariter",
  "The Parable of the Lost Coin": "Das Gleichnis vom verlorenen Groschen",
  "The Parable of the Lost Sheep": "Das Gleichnis vom verlorenen Schaf",
  "The Parable of the Prodigal Son": "Das Gleichnis vom verlorenen Sohn",
  "The Parable of the Sower": "Das Gleichnis vom Sämann",
  "The Parable of the Talents": "Das Gleichnis von den anvertrauten Talenten",
  "The Parable of the Ten Virgins": "Das Gleichnis von den zehn Jungfrauen",
  "The Parable of the Unforgiving Servant": "Das Gleichnis vom unbarmherzigen Knecht",
  "The Parable of the Wedding Feast": "Das Gleichnis vom Hochzeitsmahl",
  "The Parable of the Weeds": "Das Gleichnis vom Unkraut unter dem Weizen",
  "The Parable of the Workers in the Vineyard": "Das Gleichnis von den Arbeitern im Weinberg",
  "The Parables of Hidden Treasure and the Pearl": "Die Gleichnisse vom Schatz im Acker und der kostbaren Perle",
  "The Parables of the Mustard Seed and Leaven": "Die Gleichnisse vom Senfkorn und vom Sauerteig",
  "The Passover": "Das Passafest",
  "The Plot to Kill Jesus": "Der Plan, Jesus zu töten",
  "The Promise of Isaac": "Die Verheißung Isaaks",
  "The Promise of the Holy Spirit": "Die Verheißung des Heiligen Geistes",
  "The Purpose of Proverbs": "Sinn und Zweck der Sprüche",
  "The Race of Faith": "Der Lauf des Glaubens",
  "The Resurrection": "Die Auferstehung",
  "The Resurrection Body": "Der Auferstehungsleib",
  "The Resurrection of Christ": "Die Auferstehung Christi",
  "The Rich Young Man": "Der reiche Jüngling",
  "The Rider on the White Horse": "Der Reiter auf dem weißen Pferd",
  "The Righteous Shall Live by Faith": "Der Gerechte wird aus Glauben leben",
  "The River of Life": "Der Strom des Lebens",
  "The Sacrifice of Isaac": "Die Opferung Isaaks",
  "The Scroll and the Lamb": "Die Buchrolle und das Lamm",
  "The Sermon on the Mount": "Die Bergpredigt",
  "The Seventh Day: God Rests": "Der siebte Tag: Gott ruht",
  "The Shepherds and the Angels": "Die Hirten und die Engel",
  "The Sign of Immanuel": "Das Zeichen des Immanuel",
  "The Sixth Day: Land Animals and Humans": "Der sechste Tag: Landtiere und Menschen",
  "The Struggle with Sin": "Der Kampf mit der Sünde",
  "The Suffering Servant": "Der leidende Gottesknecht",
  "The Table of Nations": "Die Völkertafel",
  "The Temptation of Jesus": "Die Versuchung Jesu",
  "The Ten Commandments": "Die Zehn Gebote",
  "The Tenth Plague: Death of the Firstborn": "Die zehnte Plage: Tod der Erstgeborenen",
  "The Testimony of John the Baptist": "Das Zeugnis Johannes des Täufers",
  "The Thousand Years": "Das Tausendjährige Reich",
  "The Throne in Heaven": "Der Thron im Himmel",
  "The Tower of Babel": "Der Turmbau zu Babel",
  "The Transfiguration": "Die Verklärung Jesu",
  "The Triumphal Entry": "Der Einzug in Jerusalem",
  "The Truth Will Set You Free": "Die Wahrheit wird euch frei machen",
  "The Value of Wisdom": "Der Wert der Weisheit",
  "The Virtuous Woman": "Die tüchtige Frau",
  "The Visit of the Wise Men": "Die Weisen aus dem Morgenland",
  "The Way of Love": "Das Hohelied der Liebe",
  "The Way of the Righteous and the Wicked": "Der Weg der Gerechten und der Gottlosen",
  "The Wedding at Cana": "Die Hochzeit zu Kana",
  "The Woman Caught in Adultery": "Jesus und die Ehebrecherin",
  "The Word Became Flesh": "Das Wort ward Fleisch",
  "The Words of King Lemuel": "Die Worte des Königs Lemuel",
  "The Work of the Holy Spirit": "Das Wirken des Heiligen Geistes",
  "The World's Hatred": "Der Hass der Welt",
  "Three Visitors": "Die drei Besucher",
  "Treasures in Heaven": "Schätze im Himmel",
  "Trust in the Lord": "Vertraue auf den Herrn",
  "Tsadhe": "Tsadhe",
  "Unity in Christ": "Einheit in Christus",
  "Unity in the Body of Christ": "Einheit im Leib Christi",
  "Vision of the Son of Man": "Die Vision des Menschensohnes",
  "Walking by the Spirit": "Wandel im Geist",
  "Walking in the Light": "Wandel im Licht",
  "Waw": "Waw",
  "Who Is the Greatest?": "Wer ist der Größte?",
  "Wickedness in the World": "Die Bosheit der Menschen",
  "Wisdom Calls Out": "Der Ruf der Weisheit",
  "Yodh": "Yodh",
  "Zayin": "Zayin",
  "Zechariah's Prophecy": "Der Lobgesang des Zacharias",
};
export default HEADINGS_DE;
