/** Russian translations of Bible section headings */
const HEADINGS_RU: Record<string, string> = {
  "The Creation of the World": "Сотворение мира",
  "The Fourth Day: Sun, Moon, and Stars": "Четвёртый день: Солнце, Луна и звёзды",
  "The Sixth Day: Land Animals and Humans": "Шестой день: животные и человек",
  "The Seventh Day: God Rests": "Седьмой день: Бог почивает",
  "The Garden of Eden": "Эдемский сад",
  "The Creation of Woman": "Сотворение женщины",
  "The Fall of Man": "Грехопадение",
  "God's Judgment": "Суд Божий",
  "Banished from the Garden": "Изгнание из рая",
  "Cain and Abel": "Каин и Авель",
  "The Line of Cain": "Потомки Каина",
  "Seth and Enosh": "Сиф и Енос",
  "From Adam to Noah": "От Адама до Ноя",
  "Wickedness in the World": "Развращение человечества",
  "Noah and the Ark": "Ной и ковчег",
  "The Great Flood": "Великий потоп",
  "The Flood Recedes": "Окончание потопа",
  "God's Promise to Noah": "Обещание Бога Ною",
  "God's Covenant with Noah": "Завет Бога с Ноем",
  "Noah's Sons": "Сыновья Ноя",
  "The Table of Nations": "Таблица народов",
  "The Tower of Babel": "Вавилонская башня",
  "From Shem to Abram": "От Сима до Аврама",
  "The Call of Abram": "Призвание Аврама",
  "Abram in Egypt": "Аврам в Египте",
  "God's Covenant with Abram": "Завет Бога с Аврамом",
  "The Covenant of Circumcision": "Завет обрезания",
  "The Promise of Isaac": "Обетование об Исааке",
  "Three Visitors": "Три странника",
  "Abraham Pleads for Sodom": "Авраам ходатайствует за Содом",
  "The Destruction of Sodom and Gomorrah": "Гибель Содома и Гоморры",
  "Lot's Daughters": "Дочери Лота",
  "The Birth of Isaac": "Рождение Исаака",
  "Hagar and Ishmael Sent Away": "Изгнание Агари и Измаила",
  "The Sacrifice of Isaac": "Жертвоприношение Исаака",
  "Isaac and Rebekah": "Исаак и Ревекка",
  "Jacob and Esau": "Иаков и Исав",
  "Esau Sells His Birthright": "Исав продаёт первородство",
  "Jacob Steals Esau's Blessing": "Иаков похищает благословение Исава",
  "Jacob's Dream at Bethel": "Сон Иакова в Вефиле",
  "Jacob Wrestles with God": "Борьба Иакова с Богом",
  "Joseph's Dreams": "Сны Иосифа",
  "Joseph Sold by His Brothers": "Иосиф продан братьями",
  "Joseph in Potiphar's House": "Иосиф в доме Потифара",
  "Joseph Interprets Dreams in Prison": "Иосиф истолковывает сны в темнице",
  "Pharaoh's Dreams": "Сны фараона",
  "Joseph Made Ruler of Egypt": "Иосиф — правитель Египта",
  "Joseph Reveals Himself to His Brothers": "Иосиф открывается братьям",
  "The Death of Jacob": "Смерть Иакова",
  "Joseph Reassures His Brothers": "Иосиф утешает братьев",
  "Israel Oppressed in Egypt": "Израиль в египетском рабстве",
  "The Hebrew Midwives": "Еврейские повивальные бабки",
  "The Birth of Moses": "Рождение Моисея",
  "Moses Flees to Midian": "Бегство Моисея в Мадиам",
  "The Burning Bush": "Неопалимая купина",
  "The First Plague: Water to Blood": "Первая казнь: вода превращается в кровь",
  "The Passover": "Пасха",
  "The Tenth Plague: Death of the Firstborn": "Десятая казнь: смерть первенцев",
  "Crossing the Red Sea": "Переход через Красное море",
  "The Ten Commandments": "Десять заповедей",
  "The Way of the Righteous and the Wicked": "Путь праведных и нечестивых",
  "The Lord Is My Shepherd": "Господь — Пастырь мой",
  "A Prayer of Repentance": "Молитва покаяния",
  "Abiding in the Shadow of the Almighty": "Под кровом Всевышнего",
  "A Psalm of Thanksgiving": "Псалом благодарения",
  "The Glories of God's Word": "Слава Слова Божьего",
  "Beth": "Beth",
  "Gimel": "Gimel",
  "Daleth": "Daleth",
  "He": "He",
  "Waw": "Waw",
  "Zayin": "Zayin",
  "Heth": "Heth",
  "Teth": "Teth",
  "Yodh": "Yodh",
  "Kaph": "Kaph",
  "Lamedh": "Lamedh",
  "Mem": "Mem",
  "Nun": "Nun",
  "Samekh": "Samekh",
  "Ayin": "Ayin",
  "Pe": "Pe",
  "Tsadhe": "Tsadhe",
  "Qoph": "Qoph",
  "Resh": "Resh",
  "Sin and Shin": "Sin and Shin",
  "Taw": "Taw",
  "God's Perfect Knowledge": "Совершенное знание Божье",
  "Praise the Lord!": "Хвалите Господа!",
  "The Purpose of Proverbs": "Назначение притчей",
  "A Father's Instruction": "Наставление отца",
  "Wisdom Calls Out": "Премудрость взывает",
  "Trust in the Lord": "Упование на Господа",
  "The Value of Wisdom": "Ценность мудрости",
  "The Words of King Lemuel": "Слова царя Лемуила",
  "The Virtuous Woman": "Добродетельная жена",
  "Isaiah's Vision of the Lord": "Видение Исаии о Господе",
  "The Sign of Immanuel": "Знамение Еммануила",
  "A Child Is Born": "Младенец родился",
  "Comfort for God's People": "Утешение народа Божьего",
  "The Everlasting God": "Бог вечный",
  "The Suffering Servant": "Страдающий Раб",
  "An Invitation to the Thirsty": "Приглашение жаждущим",
  "The Genealogy of Jesus": "Родословие Иисуса Христа",
  "The Birth of Jesus Christ": "Рождество Иисуса Христа",
  "The Visit of the Wise Men": "Поклонение волхвов",
  "The Flight to Egypt": "Бегство в Египет",
  "Herod Kills the Children": "Избиение младенцев Иродом",
  "John the Baptist Prepares the Way": "Иоанн Креститель готовит путь",
  "The Baptism of Jesus": "Крещение Иисуса",
  "The Temptation of Jesus": "Искушение Иисуса",
  "Jesus Begins His Ministry": "Начало служения Иисуса",
  "Jesus Calls His First Disciples": "Призвание первых учеников",
  "The Sermon on the Mount": "Нагорная проповедь",
  "The Beatitudes": "Заповеди блаженства",
  "Salt and Light": "Соль и свет",
  "Christ Fulfills the Law": "Христос исполняет Закон",
  "Teaching About Anger": "Учение о гневе",
  "Teaching About Lust": "Учение о похоти",
  "Teaching About Oaths": "Учение о клятвах",
  "Teaching About Retaliation": "Учение о мести",
  "Love Your Enemies": "Любите врагов ваших",
  "Teaching About Giving": "Учение о милостыне",
  "Teaching About Prayer": "Учение о молитве",
  "The Lord's Prayer": "Молитва Господня",
  "Teaching About Fasting": "Учение о посте",
  "Treasures in Heaven": "Сокровища на небесах",
  "Do Not Worry": "Не заботьтесь",
  "Do Not Judge": "Не судите",
  "Ask, Seek, Knock": "Просите, ищите, стучите",
  "The Narrow Gate": "Тесные врата",
  "A Tree and Its Fruit": "Дерево и его плоды",
  "Build Your House on the Rock": "Дом на камне",
  "Jesus Heals a Leper": "Исцеление прокажённого",
  "The Centurion's Faith": "Вера сотника",
  "Jesus Heals Many": "Иисус исцеляет многих",
  "Jesus Calms the Storm": "Усмирение бури",
  "Jesus Heals Two Demon-Possessed Men": "Исцеление двух бесноватых",
  "The Parable of the Sower": "Притча о сеятеле",
  "The Parable of the Weeds": "Притча о плевелах",
  "The Parables of the Mustard Seed and Leaven": "Притчи о горчичном зерне и закваске",
  "The Parables of Hidden Treasure and the Pearl": "Притчи о сокрытом сокровище и жемчужине",
  "The Death of John the Baptist": "Смерть Иоанна Крестителя",
  "Jesus Feeds Five Thousand": "Насыщение пяти тысяч",
  "Jesus Walks on Water": "Иисус ходит по воде",
  "Peter's Confession of Christ": "Исповедание Петра",
  "Jesus Predicts His Death": "Иисус предсказывает Свою смерть",
  "Take Up Your Cross": "Возьмите крест свой",
  "The Transfiguration": "Преображение",
  "Who Is the Greatest?": "Кто больше?",
  "The Parable of the Lost Sheep": "Притча о заблудшей овце",
  "The Parable of the Unforgiving Servant": "Притча о немилосердном должнике",
  "Teaching About Divorce": "Учение о разводе",
  "Jesus Blesses the Children": "Благословение детей",
  "The Rich Young Man": "Богатый юноша",
  "The Parable of the Workers in the Vineyard": "Притча о работниках в винограднике",
  "Jesus Heals Two Blind Men": "Исцеление двух слепых",
  "The Triumphal Entry": "Торжественный вход в Иерусалим",
  "Jesus Cleanses the Temple": "Очищение храма",
  "The Parable of the Wedding Feast": "Притча о брачном пире",
  "Paying Taxes to Caesar": "Подать кесарю",
  "The Greatest Commandment": "Наибольшая заповедь",
  "Jesus Foretells the Future": "Иисус предсказывает будущее",
  "No One Knows the Day or Hour": "Никто не знает дня и часа",
  "The Parable of the Ten Virgins": "Притча о десяти девах",
  "The Parable of the Talents": "Притча о талантах",
  "The Final Judgment": "Страшный суд",
  "The Plot to Kill Jesus": "Заговор против Иисуса",
  "The Last Supper": "Тайная вечеря",
  "Jesus Prays in Gethsemane": "Молитва в Гефсимании",
  "The Betrayal and Arrest of Jesus": "Предательство и арест Иисуса",
  "Jesus Before the Council": "Иисус перед синедрионом",
  "Peter Denies Jesus": "Отречение Петра",
  "Jesus Before Pilate": "Иисус перед Пилатом",
  "Jesus Is Mocked": "Поругание Иисуса",
  "The Crucifixion": "Распятие",
  "The Burial of Jesus": "Погребение Иисуса",
  "The Resurrection": "Воскресение",
  "The Great Commission": "Великое поручение",
  "Jesus Drives Out an Unclean Spirit": "Иисус изгоняет нечистого духа",
  "Jesus Heals a Demon-Possessed Man": "Исцеление бесноватого",
  "Jesus Heals a Woman and Raises a Girl": "Исцеление женщины и воскрешение девочки",
  "Jesus Rejected at Nazareth": "Отвержение Иисуса в Назарете",
  "Blind Bartimaeus": "Слепой Вартимей",
  "Jesus Prays on the Mount of Olives": "Молитва на Елеонской горе",
  "Jesus Before Pilate and Herod": "Иисус перед Пилатом и Иродом",
  "The Death of Jesus": "Смерть Иисуса",
  "On the Road to Emmaus": "На пути в Эммаус",
  "Jesus Appears to His Disciples": "Явление Иисуса ученикам",
  "The Ascension": "Вознесение",
  "Introduction": "Введение",
  "The Birth of John the Baptist Foretold": "Предсказание о рождении Иоанна Крестителя",
  "The Birth of Jesus Foretold": "Благовещение о рождении Иисуса",
  "Mary Visits Elizabeth": "Мария навещает Елисавету",
  "Mary's Song of Praise": "Песнь Марии",
  "The Birth of John the Baptist": "Рождение Иоанна Крестителя",
  "Zechariah's Prophecy": "Пророчество Захарии",
  "The Birth of Jesus": "Рождение Иисуса",
  "The Shepherds and the Angels": "Пастухи и ангелы",
  "Jesus Presented at the Temple": "Сретение Господне",
  "The Boy Jesus at the Temple": "Отрок Иисус в храме",
  "Jesus Sends Out the Seventy-Two": "Иисус посылает семьдесят два ученика",
  "The Parable of the Good Samaritan": "Притча о добром самарянине",
  "Jesus Visits Martha and Mary": "Иисус в доме Марфы и Марии",
  "The Parable of the Lost Coin": "Притча о потерянной драхме",
  "The Parable of the Prodigal Son": "Притча о блудном сыне",
  "The Word Became Flesh": "Слово стало плотью",
  "The Testimony of John the Baptist": "Свидетельство Иоанна Крестителя",
  "Jesus Calls Philip and Nathanael": "Призвание Филиппа и Нафанаила",
  "The Wedding at Cana": "Брак в Кане Галилейской",
  "Jesus and Nicodemus": "Иисус и Никодим",
  "For God So Loved the World": "Ибо так возлюбил Бог мир",
  "John the Baptist Exalts Christ": "Иоанн Креститель свидетельствует о Христе",
  "Jesus and the Woman at the Well": "Иисус и самарянка",
  "Jesus Heals an Official's Son": "Исцеление сына царедворца",
  "Jesus Heals at the Pool of Bethesda": "Исцеление у купальни Вифезда",
  "The Authority of the Son": "Власть Сына",
  "Jesus the Bread of Life": "Иисус — хлеб жизни",
  "Many Disciples Turn Away": "Многие ученики отходят",
  "Jesus at the Feast of Tabernacles": "Иисус на празднике Кущей",
  "Rivers of Living Water": "Реки воды живой",
  "The Woman Caught in Adultery": "Женщина, взятая в прелюбодеянии",
  "Jesus the Light of the World": "Иисус — свет миру",
  "The Truth Will Set You Free": "Истина сделает вас свободными",
  "Jesus Heals a Man Born Blind": "Исцеление слепорождённого",
  "Jesus the Good Shepherd": "Иисус — добрый Пастырь",
  "Jesus at the Feast of Dedication": "Иисус на празднике Обновления",
  "The Death of Lazarus": "Смерть Лазаря",
  "Jesus Comforts Martha and Mary": "Иисус утешает Марфу и Марию",
  "Jesus Raises Lazarus": "Воскрешение Лазаря",
  "Mary Anoints Jesus": "Мария помазывает Иисуса",
  "Jesus Washes the Disciples' Feet": "Омовение ног учеников",
  "Jesus Predicts His Betrayal": "Иисус предсказывает предательство",
  "A New Commandment": "Новая заповедь",
  "Jesus Predicts Peter's Denial": "Предсказание об отречении Петра",
  "Jesus Comforts His Disciples": "Иисус утешает учеников",
  "I Am the Way, the Truth, and the Life": "Я есмь путь, истина и жизнь",
  "The Promise of the Holy Spirit": "Обетование Святого Духа",
  "I Am the True Vine": "Я есмь истинная виноградная лоза",
  "The Greatest Love": "Величайшая любовь",
  "The World's Hatred": "Ненависть мира",
  "The Work of the Holy Spirit": "Действие Святого Духа",
  "Sorrow Will Turn to Joy": "Печаль обратится в радость",
  "Jesus Has Overcome the World": "Иисус победил мир",
  "Jesus Prays for Himself": "Иисус молится о Себе",
  "Jesus Prays for His Disciples": "Иисус молится об учениках",
  "Jesus Prays for All Believers": "Иисус молится обо всех верующих",
  "Jesus Before the High Priest": "Иисус перед первосвященником",
  "Jesus Sentenced to Be Crucified": "Приговор к распятию",
  "The Empty Tomb": "Пустая гробница",
  "Jesus Appears to Mary Magdalene": "Явление Иисуса Марии Магдалине",
  "Jesus and Thomas": "Иисус и Фома",
  "Jesus Appears at the Sea of Galilee": "Явление Иисуса на Тивериадском море",
  "Jesus Restores Peter": "Восстановление Петра",
  "The Day of Pentecost": "День Пятидесятницы",
  "Peter's Sermon": "Проповедь Петра",
  "The First Believers": "Первые верующие",
  "The Fellowship of Believers": "Общение верующих",
  "Peter Heals a Lame Man": "Исцеление хромого Петром",
  "Peter Speaks in Solomon's Portico": "Речь Петра в притворе Соломоновом",
  "The Conversion of Saul": "Обращение Савла",
  "Saul Begins to Preach": "Савл начинает проповедовать",
  "Peter and Cornelius": "Пётр и Корнилий",
  "Paul in Thessalonica and Berea": "Павел в Фессалонике и Верии",
  "Paul in Athens": "Павел в Афинах",
  "Greetings from Paul": "Приветствие от Павла",
  "The Righteous Shall Live by Faith": "Праведный верою жив будет",
  "God's Wrath Against Sin": "Гнев Божий против греха",
  "God's Faithfulness": "Верность Божья",
  "Righteousness Through Faith": "Праведность через веру",
  "Peace with God Through Faith": "Мир с Богом через веру",
  "Death Through Adam, Life Through Christ": "Смерть через Адама, жизнь через Христа",
  "Dead to Sin, Alive in Christ": "Мертвы для греха, живы во Христе",
  "Slaves to Righteousness": "Рабы праведности",
  "The Struggle with Sin": "Борьба с грехом",
  "Life in the Spirit": "Жизнь по Духу",
  "Future Glory": "Будущая слава",
  "More Than Conquerors": "Более чем победители",
  "Salvation for All Who Believe": "Спасение для всех верующих",
  "How Beautiful Are the Feet": "Как прекрасны ноги благовестника",
  "A Living Sacrifice": "Живая жертва",
  "Marks of a True Christian": "Признаки истинного христианина",
  "Submission to Authorities": "Покорность властям",
  "Love Fulfills the Law": "Любовь — исполнение Закона",
  "The Way of Love": "Гимн любви",
  "The Resurrection of Christ": "Воскресение Христа",
  "The Resurrection Body": "Тело воскресения",
  "The Mystery of the Last Trumpet": "Тайна последней трубы",
  "Freedom in Christ": "Свобода во Христе",
  "Walking by the Spirit": "Жизнь по Духу",
  "The Fruit of the Spirit": "Плод Духа",
  "Made Alive in Christ": "Оживотворены во Христе",
  "Unity in Christ": "Единство во Христе",
  "Unity in the Body of Christ": "Единство в теле Христовом",
  "The New Life": "Новая жизнь",
  "Children and Parents": "Дети и родители",
  "The Armor of God": "Всеоружие Божье",
  "Christ's Example of Humility": "Пример смирения Христа",
  "Shining as Lights in the World": "Сияйте как светила в мире",
  "Rejoice in the Lord Always": "Радуйтесь в Господе всегда",
  "Do Not Be Anxious": "Не заботьтесь ни о чём",
  "God's Provision": "Божье обеспечение",
  "By Faith": "Верою",
  "The Race of Faith": "Подвиг веры",
  "God's Discipline": "Наказание Господне",
  "Greeting": "Приветствие",
  "Testing of Your Faith": "Испытание веры",
  "Hearing and Doing the Word": "Слышание и исполнение Слова",
  "Do Not Show Favoritism": "Не взирайте на лица",
  "Faith and Works": "Вера и дела",
  "Taming the Tongue": "Обуздание языка",
  "Walking in the Light": "Хождение во свете",
  "Children of God": "Дети Божьи",
  "Test the Spirits": "Испытывайте духов",
  "God Is Love": "Бог есть любовь",
  "Prologue": "Пролог",
  "Vision of the Son of Man": "Видение Сына Человеческого",
  "The Throne in Heaven": "Престол на небесах",
  "The Scroll and the Lamb": "Свиток и Агнец",
  "A Great Multitude from Every Nation": "Великое множество из всех народов",
  "The Marriage Supper of the Lamb": "Брачная вечеря Агнца",
  "The Rider on the White Horse": "Всадник на белом коне",
  "The Thousand Years": "Тысячелетнее царство",
  "The Great White Throne Judgment": "Суд у великого белого престола",
  "A New Heaven and a New Earth": "Новое небо и новая земля",
  "The New Jerusalem": "Новый Иерусалим",
  "The River of Life": "Река жизни",
  "Jesus Is Coming Soon": "Иисус грядёт скоро",
  "Matthias Chosen to Replace Judas": "Избрание Матфия на место Иуды",
};
export default HEADINGS_RU;
