/** Ukrainian translations of Bible section headings */
const HEADINGS_UK: Record<string, string> = {
  "The Creation of the World": "Створення світу",
  "The Fourth Day: Sun, Moon, and Stars": "Четвертий день: сонце, місяць і зорі",
  "The Sixth Day: Land Animals and Humans": "Шостий день: тварини суходолу і люди",
  "The Seventh Day: God Rests": "Сьомий день: Бог відпочиває",
  "The Garden of Eden": "Едемський сад",
  "The Creation of Woman": "Створення жінки",
  "The Fall of Man": "Гріхопадіння",
  "God's Judgment": "Божий суд",
  "Banished from the Garden": "Вигнання із саду",
  "Cain and Abel": "Каїн і Авель",
  "The Line of Cain": "Нащадки Каїна",
  "Seth and Enosh": "Сиф і Енос",
  "From Adam to Noah": "Від Адама до Ноя",
  "Wickedness in the World": "Нечестивість у світі",
  "Noah and the Ark": "Ной і ковчег",
  "The Great Flood": "Великий потоп",
  "The Flood Recedes": "Відступання потопу",
  "God's Promise to Noah": "Божа обітниця Ноєві",
  "God's Covenant with Noah": "Божий завіт з Ноєм",
  "Noah's Sons": "Сини Ноя",
  "The Table of Nations": "Таблиця народів",
  "The Tower of Babel": "Вавилонська вежа",
  "From Shem to Abram": "Від Сима до Аврама",
  "The Call of Abram": "Покликання Аврама",
  "Abram in Egypt": "Аврам у Єгипті",
  "God's Covenant with Abram": "Божий завіт з Аврамом",
  "The Covenant of Circumcision": "Завіт обрізання",
  "The Promise of Isaac": "Обітниця про Ісаака",
  "Three Visitors": "Три гості",
  "Abraham Pleads for Sodom": "Авраам заступається за Содом",
  "The Destruction of Sodom and Gomorrah": "Знищення Содому і Гоморри",
  "Lot's Daughters": "Дочки Лота",
  "The Birth of Isaac": "Народження Ісаака",
  "Hagar and Ishmael Sent Away": "Вигнання Агар та Ізмаїла",
  "The Sacrifice of Isaac": "Жертвоприношення Ісаака",
  "Isaac and Rebekah": "Ісаак і Ревека",
  "Jacob and Esau": "Яків і Ісав",
  "Esau Sells His Birthright": "Ісав продає своє первородство",
  "Jacob Steals Esau's Blessing": "Яків краде благословення Ісава",
  "Jacob's Dream at Bethel": "Сон Якова у Вефілі",
  "Jacob Wrestles with God": "Яків бореться з Богом",
  "Joseph's Dreams": "Сни Йосипа",
  "Joseph Sold by His Brothers": "Брати продають Йосипа",
  "Joseph in Potiphar's House": "Йосип у домі Потіфара",
  "Joseph Interprets Dreams in Prison": "Йосип тлумачить сни у в'язниці",
  "Pharaoh's Dreams": "Сни фараона",
  "Joseph Made Ruler of Egypt": "Йосип стає правителем Єгипту",
  "Joseph Reveals Himself to His Brothers": "Йосип відкривається братам",
  "The Death of Jacob": "Смерть Якова",
  "Joseph Reassures His Brothers": "Йосип заспокоює своїх братів",
  "Israel Oppressed in Egypt": "Гноблення Ізраїлю в Єгипті",
  "The Hebrew Midwives": "Єврейські повитухи",
  "The Birth of Moses": "Народження Мойсея",
  "Moses Flees to Midian": "Мойсей тікає до Мадіяму",
  "The Burning Bush": "Неопалима купина",
  "The First Plague: Water to Blood": "Перша кара: вода стає кров'ю",
  "The Passover": "Пасха",
  "The Tenth Plague: Death of the Firstborn": "Десята кара: смерть первістків",
  "Crossing the Red Sea": "Перехід через Червоне море",
  "The Ten Commandments": "Десять заповідей",
  "The Way of the Righteous and the Wicked": "Шлях праведних і нечестивих",
  "The Lord Is My Shepherd": "Господь — мій пастир",
  "A Prayer of Repentance": "Молитва покаяння",
  "Abiding in the Shadow of the Almighty": "Перебування під покровом Всевишнього",
  "A Psalm of Thanksgiving": "Псалом подяки",
  "The Glories of God's Word": "Слава Божого слова",
  "Beth": "Beth",
  "Gimel": "Gimel",
  "Daleth": "Daleth",
  "He": "He",
  "Waw": "Waw",
  "Zayin": "Zayin",
  "Heth": "Heth",
  "Teth": "Teth",
  "Yodh": "Yodh",
  "Kaph": "Kaph",
  "Lamedh": "Lamedh",
  "Mem": "Mem",
  "Nun": "Nun",
  "Samekh": "Samekh",
  "Ayin": "Ayin",
  "Pe": "Pe",
  "Tsadhe": "Tsadhe",
  "Qoph": "Qoph",
  "Resh": "Resh",
  "Sin and Shin": "Sin and Shin",
  "Taw": "Taw",
  "God's Perfect Knowledge": "Досконале знання Боже",
  "Praise the Lord!": "Хваліте Господа!",
  "The Purpose of Proverbs": "Призначення приповістей",
  "A Father's Instruction": "Настанова батька",
  "Wisdom Calls Out": "Мудрість кличе",
  "Trust in the Lord": "Надія на Господа",
  "The Value of Wisdom": "Цінність мудрості",
  "The Words of King Lemuel": "Слова царя Лемуїла",
  "The Virtuous Woman": "Доброчесна жінка",
  "Isaiah's Vision of the Lord": "Видіння Ісаї про Господа",
  "The Sign of Immanuel": "Знамення Еммануїла",
  "A Child Is Born": "Дитина народилася",
  "Comfort for God's People": "Потіха для Божого народу",
  "The Everlasting God": "Вічний Бог",
  "The Suffering Servant": "Страждущий слуга",
  "An Invitation to the Thirsty": "Запрошення спраглих",
  "The Genealogy of Jesus": "Родовід Ісуса",
  "The Birth of Jesus Christ": "Народження Ісуса Христа",
  "The Visit of the Wise Men": "Поклоніння мудреців",
  "The Flight to Egypt": "Втеча до Єгипту",
  "Herod Kills the Children": "Ірод убиває дітей",
  "John the Baptist Prepares the Way": "Іван Хреститель готує шлях",
  "The Baptism of Jesus": "Хрещення Ісуса",
  "The Temptation of Jesus": "Спокушення Ісуса",
  "Jesus Begins His Ministry": "Ісус починає служіння",
  "Jesus Calls His First Disciples": "Ісус покликає перших учнів",
  "The Sermon on the Mount": "Нагірна проповідь",
  "The Beatitudes": "Заповіді блаженства",
  "Salt and Light": "Сіль і світло",
  "Christ Fulfills the Law": "Христос виконує Закон",
  "Teaching About Anger": "Вчення про гнів",
  "Teaching About Lust": "Вчення про пожадливість",
  "Teaching About Oaths": "Вчення про присягу",
  "Teaching About Retaliation": "Вчення про помсту",
  "Love Your Enemies": "Любіть ворогів ваших",
  "Teaching About Giving": "Вчення про милостиню",
  "Teaching About Prayer": "Вчення про молитву",
  "The Lord's Prayer": "Молитва Господня",
  "Teaching About Fasting": "Вчення про піст",
  "Treasures in Heaven": "Скарби на небі",
  "Do Not Worry": "Не турбуйтеся",
  "Do Not Judge": "Не судіть",
  "Ask, Seek, Knock": "Просіть, шукайте, стукайте",
  "The Narrow Gate": "Вузька брама",
  "A Tree and Its Fruit": "Дерево та його плоди",
  "Build Your House on the Rock": "Будуйте дім на скелі",
  "Jesus Heals a Leper": "Ісус зцілює прокаженого",
  "The Centurion's Faith": "Віра сотника",
  "Jesus Heals Many": "Ісус зцілює багатьох",
  "Jesus Calms the Storm": "Ісус вгамовує бурю",
  "Jesus Heals Two Demon-Possessed Men": "Ісус зцілює двох біснуватих",
  "The Parable of the Sower": "Притча про сіяча",
  "The Parable of the Weeds": "Притча про кукіль",
  "The Parables of the Mustard Seed and Leaven": "Притчі про гірчичне зерно і закваску",
  "The Parables of Hidden Treasure and the Pearl": "Притчі про схований скарб і перлину",
  "The Death of John the Baptist": "Смерть Івана Хрестителя",
  "Jesus Feeds Five Thousand": "Ісус насичує п'ять тисяч",
  "Jesus Walks on Water": "Ісус ходить по воді",
  "Peter's Confession of Christ": "Визнання Петра про Христа",
  "Jesus Predicts His Death": "Ісус передвіщає свою смерть",
  "Take Up Your Cross": "Візьміть свій хрест",
  "The Transfiguration": "Преображення",
  "Who Is the Greatest?": "Хто найбільший?",
  "The Parable of the Lost Sheep": "Притча про загублену вівцю",
  "The Parable of the Unforgiving Servant": "Притча про немилосердного слугу",
  "Teaching About Divorce": "Вчення про розлучення",
  "Jesus Blesses the Children": "Ісус благословляє дітей",
  "The Rich Young Man": "Багатий юнак",
  "The Parable of the Workers in the Vineyard": "Притча про робітників у винограднику",
  "Jesus Heals Two Blind Men": "Ісус зцілює двох сліпих",
  "The Triumphal Entry": "Тріумфальний в'їзд",
  "Jesus Cleanses the Temple": "Ісус очищає храм",
  "The Parable of the Wedding Feast": "Притча про весільний бенкет",
  "Paying Taxes to Caesar": "Сплата податку кесарю",
  "The Greatest Commandment": "Найбільша заповідь",
  "Jesus Foretells the Future": "Ісус передвіщає майбутнє",
  "No One Knows the Day or Hour": "Ніхто не знає дня і години",
  "The Parable of the Ten Virgins": "Притча про десять дів",
  "The Parable of the Talents": "Притча про таланти",
  "The Final Judgment": "Останній суд",
  "The Plot to Kill Jesus": "Змова вбити Ісуса",
  "The Last Supper": "Тайна вечеря",
  "Jesus Prays in Gethsemane": "Ісус молиться в Гетсиманії",
  "The Betrayal and Arrest of Jesus": "Зрада і арешт Ісуса",
  "Jesus Before the Council": "Ісус перед синедріоном",
  "Peter Denies Jesus": "Петро зрікається Ісуса",
  "Jesus Before Pilate": "Ісус перед Пилатом",
  "Jesus Is Mocked": "Наруга над Ісусом",
  "The Crucifixion": "Розп'яття",
  "The Burial of Jesus": "Поховання Ісуса",
  "The Resurrection": "Воскресіння",
  "The Great Commission": "Велике доручення",
  "Jesus Drives Out an Unclean Spirit": "Ісус виганяє нечистого духа",
  "Jesus Heals a Demon-Possessed Man": "Ісус зцілює біснуватого",
  "Jesus Heals a Woman and Raises a Girl": "Ісус зцілює жінку і воскрешає дівчинку",
  "Jesus Rejected at Nazareth": "Ісус відкинутий у Назареті",
  "Blind Bartimaeus": "Сліпий Вартімей",
  "Introduction": "Вступ",
  "The Birth of John the Baptist Foretold": "Передвіщення народження Івана Хрестителя",
  "The Birth of Jesus Foretold": "Передвіщення народження Ісуса",
  "Mary Visits Elizabeth": "Марія відвідує Єлизавету",
  "Mary's Song of Praise": "Пісня хвали Марії",
  "The Birth of John the Baptist": "Народження Івана Хрестителя",
  "Zechariah's Prophecy": "Пророцтво Захарії",
  "The Birth of Jesus": "Народження Ісуса",
  "The Shepherds and the Angels": "Пастухи і ангели",
  "Jesus Presented at the Temple": "Принесення Ісуса до храму",
  "The Boy Jesus at the Temple": "Отрок Ісус у храмі",
  "Jesus Sends Out the Seventy-Two": "Ісус посилає сімдесят двох",
  "The Parable of the Good Samaritan": "Притча про доброго самарянина",
  "Jesus Visits Martha and Mary": "Ісус відвідує Марту і Марію",
  "The Parable of the Lost Coin": "Притча про загублену драхму",
  "The Parable of the Prodigal Son": "Притча про блудного сина",
  "Jesus Prays on the Mount of Olives": "Ісус молиться на Оливній горі",
  "Jesus Before Pilate and Herod": "Ісус перед Пилатом та Іродом",
  "The Death of Jesus": "Смерть Ісуса",
  "On the Road to Emmaus": "На дорозі до Емауса",
  "Jesus Appears to His Disciples": "Ісус з'являється учням",
  "The Ascension": "Вознесіння",
  "The Word Became Flesh": "Слово стало тілом",
  "The Testimony of John the Baptist": "Свідчення Івана Хрестителя",
  "Jesus Calls Philip and Nathanael": "Ісус покликає Филипа і Нафанаїла",
  "The Wedding at Cana": "Весілля в Кані",
  "Jesus and Nicodemus": "Ісус і Никодим",
  "For God So Loved the World": "Бо так Бог полюбив світ",
  "John the Baptist Exalts Christ": "Іван Хреститель звеличує Христа",
  "Jesus and the Woman at the Well": "Ісус і самарянка біля криниці",
  "Jesus Heals an Official's Son": "Ісус зцілює сина урядовця",
  "Jesus Heals at the Pool of Bethesda": "Ісус зцілює при купальні Вифезда",
  "The Authority of the Son": "Влада Сина",
  "Jesus the Bread of Life": "Ісус — хліб життя",
  "Many Disciples Turn Away": "Багато учнів відступають",
  "Jesus at the Feast of Tabernacles": "Ісус на святі Кучок",
  "Rivers of Living Water": "Ріки живої води",
  "The Woman Caught in Adultery": "Жінка, спіймана на перелюбі",
  "Jesus the Light of the World": "Ісус — світло світу",
  "The Truth Will Set You Free": "Правда визволить вас",
  "Jesus Heals a Man Born Blind": "Ісус зцілює сліпонародженого",
  "Jesus the Good Shepherd": "Ісус — добрий пастир",
  "Jesus at the Feast of Dedication": "Ісус на святі Оновлення",
  "The Death of Lazarus": "Смерть Лазаря",
  "Jesus Comforts Martha and Mary": "Ісус потішає Марту і Марію",
  "Jesus Raises Lazarus": "Ісус воскрешає Лазаря",
  "Mary Anoints Jesus": "Марія помазує Ісуса",
  "Jesus Washes the Disciples' Feet": "Ісус умиває ноги учням",
  "Jesus Predicts His Betrayal": "Ісус передвіщає зраду",
  "A New Commandment": "Нова заповідь",
  "Jesus Predicts Peter's Denial": "Ісус передвіщає зречення Петра",
  "Jesus Comforts His Disciples": "Ісус потішає учнів",
  "I Am the Way, the Truth, and the Life": "Я — дорога, правда і життя",
  "The Promise of the Holy Spirit": "Обітниця Святого Духа",
  "I Am the True Vine": "Я — справжній виноградний кущ",
  "The Greatest Love": "Найбільша любов",
  "The World's Hatred": "Ненависть світу",
  "The Work of the Holy Spirit": "Діяння Святого Духа",
  "Sorrow Will Turn to Joy": "Смуток обернеться радістю",
  "Jesus Has Overcome the World": "Ісус переміг світ",
  "Jesus Prays for Himself": "Ісус молиться за себе",
  "Jesus Prays for His Disciples": "Ісус молиться за учнів",
  "Jesus Prays for All Believers": "Ісус молиться за всіх віруючих",
  "Jesus Before the High Priest": "Ісус перед первосвящеником",
  "Jesus Sentenced to Be Crucified": "Ісуса засуджено на розп'яття",
  "The Empty Tomb": "Порожній гріб",
  "Jesus Appears to Mary Magdalene": "Ісус з'являється Марії Магдалині",
  "Jesus and Thomas": "Ісус і Тома",
  "Jesus Appears at the Sea of Galilee": "Ісус з'являється на Галілейському морі",
  "Jesus Restores Peter": "Ісус відновлює Петра",
  "Matthias Chosen to Replace Judas": "Обрання Матвія замість Юди",
  "The Day of Pentecost": "День П'ятидесятниці",
  "Peter's Sermon": "Проповідь Петра",
  "The First Believers": "Перші віруючі",
  "The Fellowship of Believers": "Спільнота віруючих",
  "Peter Heals a Lame Man": "Петро зцілює кульгавого",
  "Peter Speaks in Solomon's Portico": "Петро промовляє в Соломоновому ґанку",
  "The Conversion of Saul": "Навернення Савла",
  "Saul Begins to Preach": "Савло починає проповідувати",
  "Peter and Cornelius": "Петро і Корнилій",
  "Paul in Thessalonica and Berea": "Павло в Фессалоніках і Верії",
  "Paul in Athens": "Павло в Афінах",
  "Greetings from Paul": "Привітання від Павла",
  "The Righteous Shall Live by Faith": "Праведний вірою житиме",
  "God's Wrath Against Sin": "Божий гнів проти гріха",
  "God's Faithfulness": "Божа вірність",
  "Righteousness Through Faith": "Праведність через віру",
  "Peace with God Through Faith": "Мир з Богом через віру",
  "Death Through Adam, Life Through Christ": "Смерть через Адама, життя через Христа",
  "Dead to Sin, Alive in Christ": "Мертві для гріха, живі у Христі",
  "Slaves to Righteousness": "Раби праведності",
  "The Struggle with Sin": "Боротьба з гріхом",
  "Life in the Spirit": "Життя в Дусі",
  "Future Glory": "Майбутня слава",
  "More Than Conquerors": "Більш ніж переможці",
  "Salvation for All Who Believe": "Спасіння для всіх, хто вірує",
  "How Beautiful Are the Feet": "Які прекрасні ноги",
  "A Living Sacrifice": "Жива жертва",
  "Marks of a True Christian": "Ознаки справжнього християнина",
  "Submission to Authorities": "Підкорення владі",
  "Love Fulfills the Law": "Любов виконує Закон",
  "The Way of Love": "Шлях любові",
  "The Resurrection of Christ": "Воскресіння Христа",
  "The Resurrection Body": "Тіло воскресіння",
  "The Mystery of the Last Trumpet": "Таємниця останньої сурми",
  "Freedom in Christ": "Свобода у Христі",
  "Walking by the Spirit": "Ходіння Духом",
  "The Fruit of the Spirit": "Плід Духа",
  "Made Alive in Christ": "Оживлені у Христі",
  "Unity in Christ": "Єдність у Христі",
  "Unity in the Body of Christ": "Єдність у тілі Христовому",
  "The New Life": "Нове життя",
  "Children and Parents": "Діти і батьки",
  "The Armor of God": "Божа зброя",
  "Christ's Example of Humility": "Приклад смирення Христа",
  "Shining as Lights in the World": "Сяяти як світила у світі",
  "Rejoice in the Lord Always": "Радійте в Господі завжди",
  "Do Not Be Anxious": "Не турбуйтеся ні про що",
  "God's Provision": "Боже забезпечення",
  "By Faith": "Вірою",
  "The Race of Faith": "Змагання віри",
  "God's Discipline": "Боже виховання",
  "Greeting": "Привітання",
  "Testing of Your Faith": "Випробування вашої віри",
  "Hearing and Doing the Word": "Слухати і виконувати слово",
  "Do Not Show Favoritism": "Не лицемірте",
  "Faith and Works": "Віра і діла",
  "Taming the Tongue": "Приборкання язика",
  "Walking in the Light": "Ходіння в світлі",
  "Children of God": "Діти Божі",
  "Test the Spirits": "Випробовуйте духів",
  "God Is Love": "Бог є любов",
  "Prologue": "Пролог",
  "Vision of the Son of Man": "Видіння Сина Людського",
  "The Throne in Heaven": "Престол на небі",
  "The Scroll and the Lamb": "Сувій і Агнець",
  "A Great Multitude from Every Nation": "Великий натовп з кожного народу",
  "The Marriage Supper of the Lamb": "Весільна вечеря Агнця",
  "The Rider on the White Horse": "Вершник на білому коні",
  "The Thousand Years": "Тисячолітнє царство",
  "The Great White Throne Judgment": "Суд великого білого престолу",
  "A New Heaven and a New Earth": "Нове небо і нова земля",
  "The New Jerusalem": "Новий Єрусалим",
  "The River of Life": "Ріка життя",
  "Jesus Is Coming Soon": "Ісус скоро прийде",
};
export default HEADINGS_UK;
