/** Spanish translations of Bible section headings */
const HEADINGS_ES: Record<string, string> = {
  // ============ GENESIS ============
  "The Creation of the World": "La Creación del Mundo",
  "The Fourth Day: Sun, Moon, and Stars": "El Cuarto Día: Sol, Luna y Estrellas",
  "The Sixth Day: Land Animals and Humans": "El Sexto Día: Animales Terrestres y Humanos",
  "The Seventh Day: God Rests": "El Séptimo Día: Dios Reposa",
  "The Garden of Eden": "El Jardín del Edén",
  "The Creation of Woman": "La Creación de la Mujer",
  "The Fall of Man": "La Caída del Hombre",
  "God's Judgment": "El Juicio de Dios",
  "Banished from the Garden": "Expulsados del Jardín",
  "Cain and Abel": "Caín y Abel",
  "The Line of Cain": "La Descendencia de Caín",
  "Seth and Enosh": "Set y Enós",
  "From Adam to Noah": "De Adán a Noé",
  "Wickedness in the World": "La Maldad en el Mundo",
  "Noah and the Ark": "Noé y el Arca",
  "The Great Flood": "El Gran Diluvio",
  "The Flood Recedes": "Las Aguas del Diluvio Se Retiran",
  "God's Promise to Noah": "La Promesa de Dios a Noé",
  "God's Covenant with Noah": "El Pacto de Dios con Noé",
  "Noah's Sons": "Los Hijos de Noé",
  "The Table of Nations": "La Tabla de las Naciones",
  "The Tower of Babel": "La Torre de Babel",
  "From Shem to Abram": "De Sem a Abram",
  "The Call of Abram": "El Llamado de Abram",
  "Abram in Egypt": "Abram en Egipto",
  "God's Covenant with Abram": "El Pacto de Dios con Abram",
  "The Covenant of Circumcision": "El Pacto de la Circuncisión",
  "The Promise of Isaac": "La Promesa de Isaac",
  "Three Visitors": "Tres Visitantes",
  "Abraham Pleads for Sodom": "Abraham Intercede por Sodoma",
  "The Destruction of Sodom and Gomorrah": "La Destrucción de Sodoma y Gomorra",
  "Lot's Daughters": "Las Hijas de Lot",
  "The Birth of Isaac": "El Nacimiento de Isaac",
  "Hagar and Ishmael Sent Away": "Agar e Ismael Son Despedidos",
  "The Sacrifice of Isaac": "El Sacrificio de Isaac",
  "Isaac and Rebekah": "Isaac y Rebeca",
  "Jacob and Esau": "Jacob y Esaú",
  "Esau Sells His Birthright": "Esaú Vende Su Primogenitura",
  "Jacob Steals Esau's Blessing": "Jacob Roba la Bendición de Esaú",
  "Jacob's Dream at Bethel": "El Sueño de Jacob en Betel",
  "Jacob Wrestles with God": "Jacob Lucha con Dios",
  "Joseph's Dreams": "Los Sueños de José",
  "Joseph Sold by His Brothers": "José Vendido por Sus Hermanos",
  "Joseph in Potiphar's House": "José en la Casa de Potifar",
  "Joseph Interprets Dreams in Prison": "José Interpreta Sueños en la Prisión",
  "Pharaoh's Dreams": "Los Sueños del Faraón",
  "Joseph Made Ruler of Egypt": "José Es Hecho Gobernador de Egipto",
  "Joseph Reveals Himself to His Brothers": "José Se Da a Conocer a Sus Hermanos",
  "The Death of Jacob": "La Muerte de Jacob",
  "Joseph Reassures His Brothers": "José Tranquiliza a Sus Hermanos",

  // ============ EXODUS ============
  "Israel Oppressed in Egypt": "Israel Oprimido en Egipto",
  "The Hebrew Midwives": "Las Parteras Hebreas",
  "The Birth of Moses": "El Nacimiento de Moisés",
  "Moses Flees to Midian": "Moisés Huye a Madián",
  "The Burning Bush": "La Zarza Ardiente",
  "The First Plague: Water to Blood": "La Primera Plaga: El Agua Convertida en Sangre",
  "The Passover": "La Pascua",
  "The Tenth Plague: Death of the Firstborn": "La Décima Plaga: La Muerte de los Primogénitos",
  "Crossing the Red Sea": "El Cruce del Mar Rojo",
  "The Ten Commandments": "Los Diez Mandamientos",

  // ============ PSALMS ============
  "The Way of the Righteous and the Wicked": "El Camino del Justo y del Impío",
  "The Lord Is My Shepherd": "El Señor Es Mi Pastor",
  "A Prayer of Repentance": "Una Oración de Arrepentimiento",
  "Abiding in the Shadow of the Almighty": "Al Abrigo del Altísimo",
  "A Psalm of Thanksgiving": "Salmo de Acción de Gracias",
  "The Glories of God's Word": "Las Glorias de la Palabra de Dios",
  "Beth": "Beth",
  "Gimel": "Gimel",
  "Daleth": "Daleth",
  "He": "He",
  "Waw": "Waw",
  "Zayin": "Zayin",
  "Heth": "Heth",
  "Teth": "Teth",
  "Yodh": "Yodh",
  "Kaph": "Kaph",
  "Lamedh": "Lamedh",
  "Mem": "Mem",
  "Nun": "Nun",
  "Samekh": "Samekh",
  "Ayin": "Ayin",
  "Pe": "Pe",
  "Tsadhe": "Tsadhe",
  "Qoph": "Qoph",
  "Resh": "Resh",
  "Sin and Shin": "Sin and Shin",
  "Taw": "Taw",
  "God's Perfect Knowledge": "El Conocimiento Perfecto de Dios",
  "Praise the Lord!": "¡Alabad al Señor!",

  // ============ PROVERBS ============
  "The Purpose of Proverbs": "El Propósito de los Proverbios",
  "A Father's Instruction": "La Instrucción de un Padre",
  "Wisdom Calls Out": "La Sabiduría Clama",
  "Trust in the Lord": "Confía en el Señor",
  "The Value of Wisdom": "El Valor de la Sabiduría",
  "The Words of King Lemuel": "Las Palabras del Rey Lemuel",
  "The Virtuous Woman": "La Mujer Virtuosa",

  // ============ ISAIAH ============
  "Isaiah's Vision of the Lord": "La Visión de Isaías del Señor",
  "The Sign of Immanuel": "La Señal de Emanuel",
  "A Child Is Born": "Un Niño Nos Es Nacido",
  "Comfort for God's People": "Consuelo para el Pueblo de Dios",
  "The Everlasting God": "El Dios Eterno",
  "The Suffering Servant": "El Siervo Sufriente",
  "An Invitation to the Thirsty": "Una Invitación a los Sedientos",

  // ============ MATTHEW ============
  "The Genealogy of Jesus": "La Genealogía de Jesús",
  "The Birth of Jesus Christ": "El Nacimiento de Jesucristo",
  "The Visit of the Wise Men": "La Visita de los Magos",
  "The Flight to Egypt": "La Huida a Egipto",
  "Herod Kills the Children": "Herodes Mata a los Niños",
  "John the Baptist Prepares the Way": "Juan el Bautista Prepara el Camino",
  "The Baptism of Jesus": "El Bautismo de Jesús",
  "The Temptation of Jesus": "La Tentación de Jesús",
  "Jesus Begins His Ministry": "Jesús Comienza Su Ministerio",
  "Jesus Calls His First Disciples": "Jesús Llama a Sus Primeros Discípulos",
  "The Sermon on the Mount": "El Sermón del Monte",
  "The Beatitudes": "Las Bienaventuranzas",
  "Salt and Light": "La Sal y la Luz",
  "Christ Fulfills the Law": "Cristo Cumple la Ley",
  "Teaching About Anger": "Enseñanza Sobre la Ira",
  "Teaching About Lust": "Enseñanza Sobre la Lujuria",
  "Teaching About Oaths": "Enseñanza Sobre los Juramentos",
  "Teaching About Retaliation": "Enseñanza Sobre la Represalia",
  "Love Your Enemies": "Amad a Vuestros Enemigos",
  "Teaching About Giving": "Enseñanza Sobre el Dar",
  "Teaching About Prayer": "Enseñanza Sobre la Oración",
  "The Lord's Prayer": "El Padrenuestro",
  "Teaching About Fasting": "Enseñanza Sobre el Ayuno",
  "Treasures in Heaven": "Tesoros en el Cielo",
  "Do Not Worry": "No Os Afanéis",
  "Do Not Judge": "No Juzguéis",
  "Ask, Seek, Knock": "Pedid, Buscad, Llamad",
  "The Narrow Gate": "La Puerta Estrecha",
  "A Tree and Its Fruit": "El Árbol y Sus Frutos",
  "Build Your House on the Rock": "Edificad Vuestra Casa Sobre la Roca",
  "Jesus Heals a Leper": "Jesús Sana a un Leproso",
  "The Centurion's Faith": "La Fe del Centurión",
  "Jesus Heals Many": "Jesús Sana a Muchos",
  "Jesus Calms the Storm": "Jesús Calma la Tempestad",
  "Jesus Heals Two Demon-Possessed Men": "Jesús Sana a Dos Endemoniados",
  "The Parable of the Sower": "La Parábola del Sembrador",
  "The Parable of the Weeds": "La Parábola de la Cizaña",
  "The Parables of the Mustard Seed and Leaven": "Las Parábolas del Grano de Mostaza y la Levadura",
  "The Parables of Hidden Treasure and the Pearl": "Las Parábolas del Tesoro Escondido y la Perla",
  "The Death of John the Baptist": "La Muerte de Juan el Bautista",
  "Jesus Feeds Five Thousand": "Jesús Alimenta a Cinco Mil",
  "Jesus Walks on Water": "Jesús Camina Sobre el Agua",
  "Peter's Confession of Christ": "La Confesión de Pedro",
  "Jesus Predicts His Death": "Jesús Anuncia Su Muerte",
  "Take Up Your Cross": "Tomad Vuestra Cruz",
  "The Transfiguration": "La Transfiguración",
  "Who Is the Greatest?": "¿Quién Es el Mayor?",
  "The Parable of the Lost Sheep": "La Parábola de la Oveja Perdida",
  "The Parable of the Unforgiving Servant": "La Parábola del Siervo que No Perdonó",
  "Teaching About Divorce": "Enseñanza Sobre el Divorcio",
  "Jesus Blesses the Children": "Jesús Bendice a los Niños",
  "The Rich Young Man": "El Joven Rico",
  "The Parable of the Workers in the Vineyard": "La Parábola de los Obreros de la Viña",
  "Jesus Heals Two Blind Men": "Jesús Sana a Dos Ciegos",
  "The Triumphal Entry": "La Entrada Triunfal",
  "Jesus Cleanses the Temple": "Jesús Purifica el Templo",
  "The Parable of the Wedding Feast": "La Parábola del Banquete de Bodas",
  "Paying Taxes to Caesar": "El Pago de Impuestos al César",
  "The Greatest Commandment": "El Gran Mandamiento",
  "Jesus Foretells the Future": "Jesús Anuncia el Futuro",
  "No One Knows the Day or Hour": "Nadie Sabe el Día ni la Hora",
  "The Parable of the Ten Virgins": "La Parábola de las Diez Vírgenes",
  "The Parable of the Talents": "La Parábola de los Talentos",
  "The Final Judgment": "El Juicio Final",
  "The Plot to Kill Jesus": "El Complot para Matar a Jesús",
  "The Last Supper": "La Última Cena",
  "Jesus Prays in Gethsemane": "Jesús Ora en Getsemaní",
  "The Betrayal and Arrest of Jesus": "La Traición y el Arresto de Jesús",
  "Jesus Before the Council": "Jesús Ante el Concilio",
  "Peter Denies Jesus": "Pedro Niega a Jesús",
  "Jesus Before Pilate": "Jesús Ante Pilato",
  "Jesus Is Mocked": "Jesús Es Burlado",
  "The Crucifixion": "La Crucifixión",
  "The Burial of Jesus": "La Sepultura de Jesús",
  "The Resurrection": "La Resurrección",
  "The Great Commission": "La Gran Comisión",

  // ============ MARK ============
  "Jesus Drives Out an Unclean Spirit": "Jesús Expulsa a un Espíritu Inmundo",
  "Jesus Heals a Demon-Possessed Man": "Jesús Sana a un Endemoniado",
  "Jesus Heals a Woman and Raises a Girl": "Jesús Sana a una Mujer y Resucita a una Niña",
  "Jesus Rejected at Nazareth": "Jesús Es Rechazado en Nazaret",
  "Blind Bartimaeus": "El Ciego Bartimeo",

  // ============ LUKE ============
  "Introduction": "Introducción",
  "The Birth of John the Baptist Foretold": "El Anuncio del Nacimiento de Juan el Bautista",
  "The Birth of Jesus Foretold": "El Anuncio del Nacimiento de Jesús",
  "Mary Visits Elizabeth": "María Visita a Elisabet",
  "Mary's Song of Praise": "El Cántico de María",
  "The Birth of John the Baptist": "El Nacimiento de Juan el Bautista",
  "Zechariah's Prophecy": "La Profecía de Zacarías",
  "The Birth of Jesus": "El Nacimiento de Jesús",
  "The Shepherds and the Angels": "Los Pastores y los Ángeles",
  "Jesus Presented at the Temple": "Jesús Presentado en el Templo",
  "The Boy Jesus at the Temple": "El Niño Jesús en el Templo",
  "Jesus Sends Out the Seventy-Two": "Jesús Envía a los Setenta y Dos",
  "The Parable of the Good Samaritan": "La Parábola del Buen Samaritano",
  "Jesus Visits Martha and Mary": "Jesús Visita a Marta y María",
  "The Parable of the Lost Coin": "La Parábola de la Moneda Perdida",
  "The Parable of the Prodigal Son": "La Parábola del Hijo Pródigo",
  "Jesus Prays on the Mount of Olives": "Jesús Ora en el Monte de los Olivos",
  "Jesus Before Pilate and Herod": "Jesús Ante Pilato y Herodes",
  "The Death of Jesus": "La Muerte de Jesús",
  "On the Road to Emmaus": "En el Camino a Emaús",
  "Jesus Appears to His Disciples": "Jesús Se Aparece a Sus Discípulos",
  "The Ascension": "La Ascensión",

  // ============ JOHN ============
  "The Word Became Flesh": "El Verbo Se Hizo Carne",
  "The Testimony of John the Baptist": "El Testimonio de Juan el Bautista",
  "Jesus Calls Philip and Nathanael": "Jesús Llama a Felipe y a Natanael",
  "The Wedding at Cana": "Las Bodas de Caná",
  "Jesus and Nicodemus": "Jesús y Nicodemo",
  "For God So Loved the World": "Porque de Tal Manera Amó Dios al Mundo",
  "John the Baptist Exalts Christ": "Juan el Bautista Exalta a Cristo",
  "Jesus and the Woman at the Well": "Jesús y la Mujer Samaritana",
  "Jesus Heals an Official's Son": "Jesús Sana al Hijo de un Funcionario",
  "Jesus Heals at the Pool of Bethesda": "Jesús Sana en el Estanque de Betesda",
  "The Authority of the Son": "La Autoridad del Hijo",
  "Jesus the Bread of Life": "Jesús, el Pan de Vida",
  "Many Disciples Turn Away": "Muchos Discípulos Se Apartan",
  "Jesus at the Feast of Tabernacles": "Jesús en la Fiesta de los Tabernáculos",
  "Rivers of Living Water": "Ríos de Agua Viva",
  "The Woman Caught in Adultery": "La Mujer Sorprendida en Adulterio",
  "Jesus the Light of the World": "Jesús, la Luz del Mundo",
  "The Truth Will Set You Free": "La Verdad Os Hará Libres",
  "Jesus Heals a Man Born Blind": "Jesús Sana a un Ciego de Nacimiento",
  "Jesus the Good Shepherd": "Jesús, el Buen Pastor",
  "Jesus at the Feast of Dedication": "Jesús en la Fiesta de la Dedicación",
  "The Death of Lazarus": "La Muerte de Lázaro",
  "Jesus Comforts Martha and Mary": "Jesús Consuela a Marta y María",
  "Jesus Raises Lazarus": "Jesús Resucita a Lázaro",
  "Mary Anoints Jesus": "María Unge a Jesús",
  "Jesus Washes the Disciples' Feet": "Jesús Lava los Pies de Sus Discípulos",
  "Jesus Predicts His Betrayal": "Jesús Anuncia Su Traición",
  "A New Commandment": "Un Mandamiento Nuevo",
  "Jesus Predicts Peter's Denial": "Jesús Anuncia la Negación de Pedro",
  "Jesus Comforts His Disciples": "Jesús Consuela a Sus Discípulos",
  "I Am the Way, the Truth, and the Life": "Yo Soy el Camino, la Verdad y la Vida",
  "The Promise of the Holy Spirit": "La Promesa del Espíritu Santo",
  "I Am the True Vine": "Yo Soy la Vid Verdadera",
  "The Greatest Love": "El Amor Más Grande",
  "The World's Hatred": "El Odio del Mundo",
  "The Work of the Holy Spirit": "La Obra del Espíritu Santo",
  "Sorrow Will Turn to Joy": "La Tristeza Se Convertirá en Gozo",
  "Jesus Has Overcome the World": "Jesús Ha Vencido al Mundo",
  "Jesus Prays for Himself": "Jesús Ora por Sí Mismo",
  "Jesus Prays for His Disciples": "Jesús Ora por Sus Discípulos",
  "Jesus Prays for All Believers": "Jesús Ora por Todos los Creyentes",
  "Jesus Before the High Priest": "Jesús Ante el Sumo Sacerdote",
  "Jesus Sentenced to Be Crucified": "Jesús Sentenciado a Ser Crucificado",
  "The Empty Tomb": "La Tumba Vacía",
  "Jesus Appears to Mary Magdalene": "Jesús Se Aparece a María Magdalena",
  "Jesus and Thomas": "Jesús y Tomás",
  "Jesus Appears at the Sea of Galilee": "Jesús Se Aparece Junto al Mar de Galilea",
  "Jesus Restores Peter": "Jesús Restaura a Pedro",

  // ============ ACTS ============
  "Matthias Chosen to Replace Judas": "Matías Es Elegido para Reemplazar a Judas",
  "The Day of Pentecost": "El Día de Pentecostés",
  "Peter's Sermon": "El Sermón de Pedro",
  "The First Believers": "Los Primeros Creyentes",
  "The Fellowship of Believers": "La Comunión de los Creyentes",
  "Peter Heals a Lame Man": "Pedro Sana a un Cojo",
  "Peter Speaks in Solomon's Portico": "Pedro Habla en el Pórtico de Salomón",
  "The Conversion of Saul": "La Conversión de Saulo",
  "Saul Begins to Preach": "Saulo Comienza a Predicar",
  "Peter and Cornelius": "Pedro y Cornelio",
  "Paul in Thessalonica and Berea": "Pablo en Tesalónica y Berea",
  "Paul in Athens": "Pablo en Atenas",

  // ============ ROMANS ============
  "Greetings from Paul": "Saludos de Pablo",
  "The Righteous Shall Live by Faith": "El Justo Vivirá por la Fe",
  "God's Wrath Against Sin": "La Ira de Dios Contra el Pecado",
  "God's Faithfulness": "La Fidelidad de Dios",
  "Righteousness Through Faith": "La Justicia por Medio de la Fe",
  "Peace with God Through Faith": "Paz con Dios por Medio de la Fe",
  "Death Through Adam, Life Through Christ": "Muerte por Adán, Vida por Cristo",
  "Dead to Sin, Alive in Christ": "Muertos al Pecado, Vivos en Cristo",
  "Slaves to Righteousness": "Esclavos de la Justicia",
  "The Struggle with Sin": "La Lucha Contra el Pecado",
  "Life in the Spirit": "La Vida en el Espíritu",
  "Future Glory": "La Gloria Venidera",
  "More Than Conquerors": "Más que Vencedores",
  "Salvation for All Who Believe": "Salvación para Todos los que Creen",
  "How Beautiful Are the Feet": "¡Cuán Hermosos Son los Pies!",
  "A Living Sacrifice": "Un Sacrificio Vivo",
  "Marks of a True Christian": "Marcas de un Verdadero Cristiano",
  "Submission to Authorities": "Sometimiento a las Autoridades",
  "Love Fulfills the Law": "El Amor Cumple la Ley",

  // ============ 1 CORINTHIANS ============
  "The Way of Love": "El Camino del Amor",
  "The Resurrection of Christ": "La Resurrección de Cristo",
  "The Resurrection Body": "El Cuerpo de Resurrección",
  "The Mystery of the Last Trumpet": "El Misterio de la Última Trompeta",

  // ============ GALATIANS ============
  "Freedom in Christ": "Libertad en Cristo",
  "Walking by the Spirit": "Andad en el Espíritu",
  "The Fruit of the Spirit": "El Fruto del Espíritu",

  // ============ EPHESIANS ============
  "Made Alive in Christ": "Vivificados en Cristo",
  "Unity in Christ": "Unidad en Cristo",
  "Unity in the Body of Christ": "Unidad en el Cuerpo de Cristo",
  "The New Life": "La Nueva Vida",
  "Children and Parents": "Hijos y Padres",
  "The Armor of God": "La Armadura de Dios",

  // ============ PHILIPPIANS ============
  "Christ's Example of Humility": "El Ejemplo de Humildad de Cristo",
  "Shining as Lights in the World": "Resplandeciendo como Luminares en el Mundo",
  "Rejoice in the Lord Always": "Regocijaos en el Señor Siempre",
  "Do Not Be Anxious": "No Os Angustiéis",
  "God's Provision": "La Provisión de Dios",

  // ============ HEBREWS ============
  "By Faith": "Por la Fe",
  "The Race of Faith": "La Carrera de la Fe",
  "God's Discipline": "La Disciplina de Dios",

  // ============ JAMES ============
  "Greeting": "Saludo",
  "Testing of Your Faith": "La Prueba de Vuestra Fe",
  "Hearing and Doing the Word": "Oíd y Haced la Palabra",
  "Do Not Show Favoritism": "No Hagáis Acepción de Personas",
  "Faith and Works": "La Fe y las Obras",
  "Taming the Tongue": "La Lengua Domada",

  // ============ 1 JOHN ============
  "Walking in the Light": "Andando en la Luz",
  "Children of God": "Hijos de Dios",
  "Test the Spirits": "Probad los Espíritus",
  "God Is Love": "Dios Es Amor",

  // ============ REVELATION ============
  "Prologue": "Prólogo",
  "Vision of the Son of Man": "Visión del Hijo del Hombre",
  "The Throne in Heaven": "El Trono en el Cielo",
  "The Scroll and the Lamb": "El Rollo y el Cordero",
  "A Great Multitude from Every Nation": "Una Gran Multitud de Todas las Naciones",
  "The Marriage Supper of the Lamb": "La Cena de las Bodas del Cordero",
  "The Rider on the White Horse": "El Jinete del Caballo Blanco",
  "The Thousand Years": "Los Mil Años",
  "The Great White Throne Judgment": "El Juicio del Gran Trono Blanco",
  "A New Heaven and a New Earth": "Un Cielo Nuevo y una Tierra Nueva",
  "The New Jerusalem": "La Nueva Jerusalén",
  "The River of Life": "El Río de la Vida",
  "Jesus Is Coming Soon": "Jesús Viene Pronto",
};
export default HEADINGS_ES;
